version: 2
updates:
  - package-ecosystem: npm
    directory: /src/ClientApp
    schedule:
      interval: monthly
    labels:
      - dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
  - package-ecosystem: nuget
    directory: /src
    schedule:
      interval: monthly
    labels:
      - dependencies
