language: node_js
node_js:
    - "lts/*"
before_install:
    - cd src/ClientApp
    - npm install -g npm
    - npm install -g grunt-cli
notifications:
    email:
        on_success: change
        on_failure: change
sudo: required
cache: npm
addons:
    chrome: stable
