services:
  api:
    image: parole/api
    build:
      context: .
      dockerfile: ./src/Dockerfile
    volumes:
      - ${HOME}/.aspnet/https:/https/

  cache:
    image: redis:6
    ports:
     - 6379:6379
