const supervisionItems = [
  {
    name: 'CCC',
    id: 'ccc',
  },
  {
    name: 'PVP',
    id: 'pvp',
  },
  {
    name: 'COMP',
    id: 'comp',
  },
  {
    name: 'DEP',
    id: 'dep',
  },
  {
    name: 'EM',
    id: 'em',
  },
  {
    name: 'GPS',
    id: 'gps',
  },
  {
    name: 'SO',
    id: 'so',
  },
  {
    name: 'SO-A',
    id: 'soa',
  },
  {
    name: 'SO-B',
    id: 'sob',
  },
  {
    name: 'SO-C',
    id: 'soc',
  },
  {
    name: 'FUG',
    id: 'fug',
  },
  {
    name: 'INCAR',
    id: 'incar',
  },
  {
    name: 'RESID',
    id: 'resid',
  },
  {
    name: 'DRUG CT',
    id: 'drugct',
  },
  {
    name: 'DORA',
    id: 'dora',
  },
  {
    name: 'ECR',
    id: 'ecr',
  },
  {
    name: 'FOSI',
    id: 'fosi',
  },
  {
    name: 'IG INT',
    id: 'igint',
  },
  {
    name: 'MIO',
    id: 'mio',
  },
];

const mainGangs = [
  {
    name: 'sureno',
    id: 'sureno',
  },
  {
    name: 'nortenos',
    id: 'nortenos',
  },
  {
    name: 'omg - outlaw motorcycl',
    id: 'omg',
  },
  {
    name: 'white supremacist',
    id: 'ws',
  },
  {
    name: 'crip',
    id: 'crip',
  },
  {
    name: 'bloods',
    id: 'blood',
  },
  {
    name: 'people nation',
    id: 'pn',
  },
  {
    name: 'folk nation',
    id: 'fn',
  },
  {
    name: 'others',
    id: 'o',
  },
  {
    name: 'no type specified',
    id: 'none',
  },
  {
    name: 'vlt',
    id: 'vlt',
  },
  {
    name: 'o13',
    id: '13',
  },
  {
    name: 'qvo',
    id: 'qvo',
  },
];

const offenseTypes = [
  {
    name: 'murder',
    id: 'A',
  },
  {
    name: 'sex/registerable',
    id: 'D',
  },
  {
    name: 'sex/non-registerable',
    id: 'E',
  },
  {
    name: 'person',
    id: 'G',
  },
  {
    name: 'alcohol & drug',
    id: 'J',
  },
  {
    name: 'property',
    id: 'M',
  },
  {
    name: 'weapons',
    id: 'P',
  },
  {
    name: 'driving',
    id: 'S',
  },
  {
    name: 'other',
    id: 'V',
  },
  {
    name: 'drug possession only',
    id: 'X',
  },
  {
    name: 'unknown',
    id: 'Z',
  },
];

const agentLookup = [
  { value: 'AARON LEE', id: 176268, supervisor: 'KIRK LAMBERT' },
  { value: 'AARON POWELL', id: 205182, supervisor: 'VIDA BETTS' },
  { value: 'AARON SMITH', id: 166086, supervisor: 'KODY FLOYD' },
  { value: 'ADAM CHARD', id: 169801, supervisor: 'MICHAEL RENCKERT' },
  { value: 'ALAN DRESSLER', id: 182822, supervisor: 'RICHARD GLEN MORRIS' },
  { value: 'ALBERT WHITEHORSE', id: 105493, supervisor: 'WADE ALLINSON' },
  { value: 'ALEJANDRO REYES-GALDAMEZ', id: 183010, supervisor: 'DUANE REED' },
  { value: 'ALEX IPSEN', id: 194472, supervisor: 'CATHERINE GUNDERSON' },
  { value: 'ALIE CARLSON', id: 198635, supervisor: 'WILLIAM MORELL' },
  { value: 'ALLEN JULIAN', id: 112738, supervisor: 'TONY GARRETT' },
  { value: 'ALLEN RUECKERT', id: 196382, supervisor: 'MARK COLBY' },
  { value: 'AMANDA PARKER', id: 145364, supervisor: 'KAYE HOUSTON' },
  { value: 'ANA M MASCIANTONIO', id: 182708, supervisor: 'SIMON K FULLER' },
  { value: 'ANDREA FERNELIUS', id: 211210, supervisor: 'KAYE HOUSTON' },
  { value: 'ANDREW ARCHULETA', id: 199003, supervisor: 'GREG SMITH' },
  { value: 'ANDREW DALTON', id: 196368, supervisor: 'CLINTON LUND' },
  { value: 'ANDREW HAMPTON', id: 198661, supervisor: 'KILEY D WILLIS' },
  { value: 'ANDREW JOHNSON', id: 203054, supervisor: 'GREGORY PERRY' },
  { value: 'ANDREW WALKER', id: 196360, supervisor: 'SIMON K FULLER' },
  { value: 'ANDY V PHAM', id: 188455, supervisor: 'TERRY BANKS' },
  { value: 'ANGELA HENDRIX', id: 143739, supervisor: 'IRVIN B. HALE' },
  { value: 'ANTHONY CANDELARIA', id: 166089, supervisor: 'SIMON K FULLER' },
  { value: 'ARTURO DUARTE', id: 201167, supervisor: 'RANDI CARTER' },
  { value: 'ASHLEY POWELL', id: 211792, supervisor: 'ERIK OLSEN' },
  { value: 'AUDREY BROWN', id: 158655, supervisor: 'KATIE CARVER' },
  { value: 'AUSTIN BRACKEN', id: 182981, supervisor: 'GREGORY PERRY' },
  { value: 'AUSTIN RHEES', id: 194509, supervisor: 'CATHERINE GUNDERSON' },
  { value: 'BARRY HANSEN', id: 106821, supervisor: 'JAMES CLEGG' },
  { value: 'BEAU BROMLEY', id: 164036, supervisor: 'JASON LOERTSCHER' },
  { value: 'BEN BROADBENT', id: 205420, supervisor: 'ELDON HAMELIN' },
  { value: 'BERNADETTE DEFISHER', id: 212840, supervisor: 'JOSLYN PILLING' },
  { value: 'BLAINE BILLS', id: 112112, supervisor: 'KIRK LAMBERT' },
  { value: 'BLAKE SESSIONS', id: 210308, supervisor: 'ROBERT CID' },
  { value: 'BLAKE WRIGHT', id: 102267, supervisor: 'KEVIN HIZER' },
  { value: 'BOB CHASTAIN', id: 184234, supervisor: 'MICHAEL RENCKERT' },
  { value: 'BOYD GLEDHILL', id: 105454, supervisor: 'LUKE LASSITER' },
  { value: 'BRAD D LUND', id: 192689, supervisor: 'KATIE CARVER' },
  { value: 'BRAD DRAPER', id: 114063, supervisor: 'ELDON HAMELIN' },
  { value: 'BRAD JOHNSON', id: 190286, supervisor: 'JASON LOERTSCHER' },
  { value: 'BRADY BARNEY', id: 198358, supervisor: 'ALLEN JULIAN' },
  { value: 'BRANDON K VOYLES', id: 189784, supervisor: 'RUBEN CERVANTES' },
  { value: 'BRANDON PIXTON', id: 154944, supervisor: 'GREGORY PERRY' },
  { value: 'BRANDON W MEADOWS', id: 191429, supervisor: 'SIMON K FULLER' },
  { value: 'BRANT HODSON', id: 196985, supervisor: 'RICK SMITH' },
  { value: 'BREANN KEMP', id: 216756, supervisor: 'TANYA DIANA' },
  { value: 'BRENDA OLIEKAN', id: 117481, supervisor: 'BRANDI HERRERA' },
  { value: 'BRETT BUTLER', id: 113434, supervisor: 'DAVID TRAHAN' },
  { value: 'BRETT CURTIS', id: 164645, supervisor: 'DANIEL HAYS' },
  { value: 'BRETT LARSEN', id: 175211, supervisor: 'DANIEL HAYS' },
  { value: 'BRIAN K. LYTHGOE', id: 160737, supervisor: 'RYAN PROCTOR' },
  { value: 'BRIAN M ANHDER', id: 189824, supervisor: 'WILLIAM MORELL' },
  { value: 'BRITTANY ROTHE', id: 195409, supervisor: 'DANIEL SCHUGK' },
  { value: 'BROC HUNTSMAN', id: 187276, supervisor: 'JAMES GARRETT' },
  { value: 'BRYAN JOHNSON', id: 181717, supervisor: 'KIRK LAMBERT' },
  { value: 'BRYAN S BRITTON', id: 184233, supervisor: 'CATHERINE GUNDERSON' },
  { value: 'BRYAN S. AITKEN', id: 165351, supervisor: 'GREG SMITH' },
  { value: 'BRYANT COOK', id: 215213, supervisor: 'ELDON HAMELIN' },
  { value: 'BRYCE ATKIN', id: 201933, supervisor: 'STEVE WILLIAMSON' },
  { value: 'BRYON MELOT', id: 200576, supervisor: 'AUSTIN Q ROBERTS' },
  { value: 'CADEN WALKER', id: 202326, supervisor: 'TODD GRAHAM' },
  { value: 'CAITLYN GURR', id: 0, supervisor: 'LUKE LASSITER' },
  { value: 'CALVIN N. PICKETT', id: 147590, supervisor: 'ALLEN JULIAN' },
  { value: 'CAMILLE M CHRISTENSEN', id: 140653, supervisor: 'RANDI CARTER' },
  { value: 'CANDACE DOMINGO', id: 130935, supervisor: 'MITCHELL CARVER' },
  { value: 'CARLTON NIELSEN', id: 198637, supervisor: 'DANIEL SCHUGK' },
  { value: 'CAROLYN MONTILLA', id: 172640, supervisor: 'JACOB ROMERO' },
  { value: 'CARSON CLEMMENS', id: 203008, supervisor: 'ERIK OLSEN' },
  { value: 'CASEY BARNEY', id: 203041, supervisor: 'WILLIAM MORELL' },
  { value: 'CASEY CLAWSON', id: 213292, supervisor: 'KEVIN HIZER' },
  { value: 'CHANNA ANDERSON', id: 130939, supervisor: 'VIDA BETTS' },
  { value: 'CHARLES CHAPPELL', id: 167690, supervisor: 'SIMON K FULLER' },
  { value: 'CHARLES FRAZIER', id: 176015, supervisor: 'MICHAEL RENCKERT' },
  { value: 'CHASE ARAVE', id: 199160, supervisor: 'DANIEL HAYS' },
  { value: 'CHASE WITHERS', id: 197479, supervisor: 'STEVE WILLIAMSON' },
  { value: 'CHRIS COOMBS', id: 152612, supervisor: 'DUANE REED' },
  { value: 'CHRIS FACER', id: 200471, supervisor: 'ROBERT CID' },
  { value: 'CHRIS PACKER', id: 164752, supervisor: 'MICHAEL ADAM' },
  { value: 'CHRISTA COLBY', id: 185646, supervisor: 'KAYE HOUSTON' },
  { value: 'CHRISTINA CURTIS', id: 164732, supervisor: 'KAYE HOUSTON' },
  { value: 'CHRISTINE E GONZALEZ', id: 185693, supervisor: 'RICHARD JENKINS' },
  { value: 'CHRISTINE STRONG', id: 159777, supervisor: 'ERIK OLSEN' },
  { value: 'CHRISTOPHER ASTLE', id: 187199, supervisor: 'KODY FLOYD' },
  { value: 'CHRISTOPHER BIRD', id: 172524, supervisor: 'GREG SMITH' },
  { value: 'CHRISTOPHER BOHN', id: 175994, supervisor: 'JASON LOERTSCHER' },
  { value: 'CHRISTOPHER MICKELSON', id: 139848, supervisor: 'ERIK OLSEN' },
  { value: 'CJ EVANS', id: 198625, supervisor: 'RYAN PROCTOR' },
  { value: 'CLAY YARDLEY', id: 100821, supervisor: 'JAMES CAMPOS' },
  { value: 'CLAYTON RICORD JR', id: 140513, supervisor: 'JOSEPH HERMAN' },
  { value: 'CLIFF HAMILTON', id: 208006, supervisor: 'CATHERINE GUNDERSON' },
  { value: 'CLIFFORD D CABANILLA', id: 192702, supervisor: 'ANTOINETTE AIONO' },
  { value: 'CLIFFORD HENDRY', id: 214176, supervisor: 'JUSTIN SCHELIN' },
  { value: 'CLINTON M HANSEN', id: 184252, supervisor: 'TERRY BANKS' },
  { value: 'COLE KATSILAS', id: 193618, supervisor: 'CLAUDIO B CUEVA' },
  { value: 'COREY MCEWAN', id: 171952, supervisor: 'KODY FLOYD' },
  { value: 'CORY R GRINT', id: 184184, supervisor: 'LUKE LASSITER' },
  { value: 'CRAIG HANSEN', id: 204686, supervisor: 'KILEY D WILLIS' },
  { value: 'CRYSTAL BLASI', id: 200783, supervisor: 'KIRK LAMBERT' },
  { value: 'DAMON PARCELL', id: 107846, supervisor: 'WILLIAM MORELL' },
  { value: 'DAN HEATH', id: 196365, supervisor: 'DAVID TRAHAN' },
  { value: 'DANE ISBELL', id: 182036, supervisor: 'BLAKE BEESLEY' },
  { value: 'DANIEL A. NIEBUHR', id: 160284, supervisor: 'DAVID TRAHAN' },
  { value: 'DANIEL FERRON', id: 189796, supervisor: 'KEVIN HIZER' },
  { value: 'DANIEL GORDON', id: 114442, supervisor: 'STEVE WILLIAMSON' },
  { value: 'DANIEL GUNRUD', id: 169052, supervisor: 'TERRY BANKS' },
  { value: 'DANIEL JORGENSEN', id: 134413, supervisor: 'KODY FLOYD' },
  { value: 'DANNA ALLEN', id: 155403, supervisor: 'ANTHONY BROWN' },
  { value: 'DAVE CORNELL', id: 198687, supervisor: 'DANIEL SCHUGK' },
  { value: 'DAVID AMADOR', id: 178165, supervisor: 'JASON LOERTSCHER' },
  { value: 'DAVID BEAL', id: 203017, supervisor: 'TODD GRAHAM' },
  { value: 'DAVID BUSTO', id: 197518, supervisor: 'DUANE REED' },
  { value: 'DAVID CUMMINS', id: 192931, supervisor: 'MICHAEL ADAM' },
  { value: 'DAVID GAFFNEY', id: 166498, supervisor: 'RICK SMITH' },
  { value: 'DAVID HANNA', id: 176016, supervisor: 'BLAKE BEESLEY' },
  { value: 'DAVID JENSEN', id: 164329, supervisor: 'CATHERINE GUNDERSON' },
  { value: 'DAVID JONES', id: 163407, supervisor: 'JACOB ROMERO' },
  { value: 'DAVID OWENS', id: 154429, supervisor: 'JAMES GARRETT' },
  { value: 'DAVID PEDERSEN', id: 198634, supervisor: 'GREG SMITH' },
  { value: 'DAVID PENROD', id: 187203, supervisor: 'TRACY SHOCK' },
  { value: 'DAVID YOUNG', id: 206927, supervisor: 'RANDI CARTER' },
  { value: 'DEAN ADAMS', id: 207148, supervisor: 'BLAKE BEESLEY' },
  { value: 'DEBBIE GATES', id: 164564, supervisor: 'SETH ROBINSON' },
  { value: 'DENTON CALL', id: 207962, supervisor: 'KIRK LAMBERT' },
  { value: 'DEON WALSER', id: 187762, supervisor: 'KEVIN HIZER' },
  { value: 'DEREK HOLMES', id: 194508, supervisor: 'AUSTIN Q ROBERTS' },
  { value: 'DERRICK CUMBEE', id: 195173, supervisor: 'ROBERT CID' },
  { value: 'DUSTIN ANDERSON', id: 211306, supervisor: 'VIDA BETTS' },
  { value: 'DUSTIN APPEL', id: 175696, supervisor: 'KODY FLOYD' },
  { value: 'DUSTIN P PETERSON', id: 218549, supervisor: 'LUKE LASSITER' },
  { value: 'DUSTIN R. VEATER', id: 144439, supervisor: 'RICHARD GLEN MORRIS' },
  { value: 'ELDON HAMELIN', id: 151860, supervisor: 'WADE ALLINSON' },
  { value: 'ELIANI SAMANIEGO', id: 203019, supervisor: 'GREGORY PERRY' },
  { value: 'ELIZABETH IAVASILE', id: 211984, supervisor: 'JAMES CAMPOS' },
  { value: 'ERIC S JACOBSON', id: 188426, supervisor: 'MARK COLBY' },
  { value: 'ERICK LEBRON', id: 196967, supervisor: 'TODD GRAHAM' },
  { value: 'ERIK KRUGER', id: 200043, supervisor: 'DANIEL HAYS' },
  { value: 'EVERETT WESTERMAN', id: 112334, supervisor: 'DAVID TRAHAN' },
  { value: 'GAIL ROSKELLEY', id: 104863, supervisor: 'KIRK LAMBERT' },
  { value: 'GALIT LEVANON-ARELLANO', id: 204550, supervisor: 'JOSLYN PILLING' },
  { value: 'GARY P TIDWELL', id: 192644, supervisor: 'STEVE WILLIAMSON' },
  { value: 'GERIT ASAY', id: 176283, supervisor: 'WILLIAM LUKE' },
  { value: 'GLENN C. SMITH', id: 152637, supervisor: 'KIRK LAMBERT' },
  { value: 'GREG HUNT', id: 204011, supervisor: 'SETH ROBINSON' },
  { value: 'GREG OWENS', id: 208455, supervisor: 'CATHERINE GUNDERSON' },
  { value: 'HILARY JENSEN', id: 128477, supervisor: 'JOSLYN PILLING' },
  { value: 'IAN ADAMS', id: 172447, supervisor: 'JAMES GARRETT' },
  { value: 'ILEANA PENDLEY', id: 199016, supervisor: 'SETH ROBINSON' },
  { value: 'JACLYN PACE', id: 197501, supervisor: 'GREG SMITH' },
  { value: 'JACOB COLEMAN', id: 211910, supervisor: 'STEVE WILLIAMSON' },
  { value: 'JAEME SOLIS', id: 181715, supervisor: 'JAMES CLEGG' },
  { value: 'JAKE DOWNS', id: 209418, supervisor: 'RYAN PROCTOR' },
  { value: 'JAKE HARWARD', id: 209260, supervisor: 'GREGORY PERRY' },
  { value: 'JAMES CAMPOS', id: 141679, supervisor: 'STEVE YEATES' },
  { value: 'JAMES FOSTER', id: 193651, supervisor: 'ERIK OLSEN' },
  { value: 'JAMES GARRETT', id: 149448, supervisor: 'JON KELLY MAXWELL' },
  { value: 'JAMES LEGORE', id: 141676, supervisor: 'MICHAEL RENCKERT' },
  { value: 'JAMES MORRIS', id: 204130, supervisor: 'WILLIAM MORELL' },
  { value: 'JAMES WEAVER', id: 112150, supervisor: 'VIDA BETTS' },
  { value: 'JANECA KLAYKO', id: 211299, supervisor: 'ALBERT WHITEHORSE' },
  { value: 'JARED M. MINNOCH', id: 130103, supervisor: 'JAMES CAMPOS' },
  { value: 'JARED ROSE', id: 203821, supervisor: 'RYAN PROCTOR' },
  { value: 'JARON TAYLOR', id: 210942, supervisor: 'ERIK OLSEN' },
  { value: 'JASON BEHUNIN', id: 158571, supervisor: 'RICHARD JENKINS' },
  { value: 'JASON BOWLER', id: 200601, supervisor: 'NATHAN ELDRIDGE' },
  { value: 'JASON GALLENTINE', id: 121727, supervisor: 'MARK COLBY' },
  { value: 'JASON HANSEN', id: 160997, supervisor: 'TRACY SHOCK' },
  { value: 'JASON KENNARD WILCOCK', id: 158605, supervisor: 'MITCHELL CARVER' },
  { value: 'JASON NUNEZ', id: 202355, supervisor: 'TERRY BANKS' },
  { value: 'JASON ROOTHOFF', id: 168608, supervisor: 'KILEY D WILLIS' },
  { value: 'JAY BIGLE', id: 196307, supervisor: 'RICHARD GLEN MORRIS' },
  { value: 'JAY L COATES', id: 158606, supervisor: 'DUANE REED' },
  { value: 'JAY SISSENER', id: 212294, supervisor: 'ALLEN JULIAN' },
  { value: 'JEFF BUCK', id: 204848, supervisor: 'KILEY D WILLIS' },
  { value: 'JEFFERY T HOWCROFT', id: 184235, supervisor: 'RICK SMITH' },
  { value: 'JEFFREY HANSEN', id: 176272, supervisor: 'RANDI CARTER' },
  { value: 'JEFFREY ROWLEY', id: 159177, supervisor: 'KILEY D WILLIS' },
  { value: 'JEREMY NELSON', id: 128009, supervisor: 'JAMES CAMPOS' },
  { value: 'JEREMY SHAW', id: 109983, supervisor: 'TERRY BANKS' },
  { value: 'JEROMY SAMPSON', id: 132917, supervisor: 'BRIAN HAMBLIN' },
  { value: 'JERRID DOCKERY', id: 175096, supervisor: 'JUSTIN SCHELIN' },
  { value: 'JERRY AARON', id: 176276, supervisor: 'RANDI CARTER' },
  { value: 'JERRY COOK', id: 105873, supervisor: 'KODY FLOYD' },
  { value: 'JESS A. PLOUZEK', id: 155411, supervisor: 'KATIE CARVER' },
  { value: 'JOE A MURPHY', id: 191515, supervisor: 'CATHERINE GUNDERSON' },
  { value: 'JOHN B LIVINGSTON', id: 189791, supervisor: 'ANGELA HENDRIX' },
  { value: 'JOHN B WHITED', id: 184262, supervisor: 'ANGELA HENDRIX' },
  { value: 'JOHN CARPENTER', id: 138697, supervisor: 'ERIK OLSEN' },
  { value: 'JOHN DERBIDGE', id: 169829, supervisor: 'SIMON K FULLER' },
  { value: 'JOHN KELLEY', id: 176053, supervisor: 'BRIAN HAMBLIN' },
  { value: 'JOHN POWELL', id: 186609, supervisor: 'VIDA BETTS' },
  { value: 'JOHNATHAN VASQUEZ', id: 153535, supervisor: 'VIDA BETTS' },
  { value: 'JON KELLY MAXWELL', id: 131920, supervisor: 'JAMES GARRETT' },
  { value: 'JORDAN BURGESS', id: 207017, supervisor: 'RICK SMITH' },
  { value: 'JORDAN HORST', id: 187208, supervisor: 'BLAKE BEESLEY' },
  { value: 'JORDAN LAVENTURE', id: 205224, supervisor: 'ERIK OLSEN' },
  { value: 'JORDAN P BONYAI', id: 201452, supervisor: 'CLINTON LUND' },
  { value: 'JOSEPH F. LANEY', id: 150617, supervisor: 'ALBERT WHITEHORSE' },
  { value: 'JOSH BAIRD', id: 190147, supervisor: 'DAVID TRAHAN' },
  { value: 'JOSHUA ALLRED', id: 161757, supervisor: 'TODD GRAHAM' },
  { value: 'JOSHUA MORRIS', id: 218040, supervisor: 'BRIAN HAMBLIN' },
  { value: 'JUVAL TORRES', id: 207611, supervisor: 'RYAN PROCTOR' },
];

const supervisorLookup = [
  { id: 'ALBERT WHITEHORSE', value: 'ALBERT WHITEHORSE' },
  { id: 'ALLEN JULIAN', value: 'ALLEN JULIAN' },
  { id: 'ANDREW MCCAIN', value: 'ANDREW MCCAIN' },
  { id: 'ANGELA HENDRIX', value: 'ANGELA HENDRIX' },
  { id: 'ANTHONY BROWN', value: 'ANTHONY BROWN' },
  { id: 'ANTOINETTE AIONO', value: 'ANTOINETTE AIONO' },
  { id: 'AUSTIN Q ROBERTS', value: 'AUSTIN Q ROBERTS' },
  { id: 'BART MORTENSEN', value: 'BART MORTENSEN' },
  { id: 'BLAKE BEESLEY', value: 'BLAKE BEESLEY' },
  { id: 'BRANDI HERRERA', value: 'BRANDI HERRERA' },
  { id: 'BRIAN HAMBLIN', value: 'BRIAN HAMBLIN' },
  { id: 'CATHERINE GUNDERSON', value: 'CATHERINE GUNDERSON' },
  { id: 'CLAUDIO B CUEVA', value: 'CLAUDIO B CUEVA' },
  { id: 'CLINTON LUND', value: 'CLINTON LUND' },
  { id: 'DANIEL HAYS', value: 'DANIEL HAYS' },
  { id: 'DANIEL SCHUGK', value: 'DANIEL SCHUGK' },
  { id: 'DAVID TRAHAN', value: 'DAVID TRAHAN' },
  { id: 'DUANE REED', value: 'DUANE REED' },
  { id: 'ELDON HAMELIN', value: 'ELDON HAMELIN' },
  { id: 'ERIK OLSEN', value: 'ERIK OLSEN' },
  { id: 'GREG SMITH', value: 'GREG SMITH' },
  { id: 'GREGORY PERRY', value: 'GREGORY PERRY' },
  { id: 'IRVIN B. HALE', value: 'IRVIN B. HALE' },
  { id: 'JACOB ROMERO', value: 'JACOB ROMERO' },
  { id: 'JAMES CAMPOS', value: 'JAMES CAMPOS' },
  { id: 'JAMES CLEGG', value: 'JAMES CLEGG' },
  { id: 'JAMES GARRETT', value: 'JAMES GARRETT' },
  { id: 'JASON LOERTSCHER', value: 'JASON LOERTSCHER' },
  { id: 'JENNIFER CALVO', value: 'JENNIFER CALVO' },
  { id: 'JON KELLY MAXWELL', value: 'JON KELLY MAXWELL' },
  { id: 'JOSEPH C ABBOTT', value: 'JOSEPH C ABBOTT' },
  { id: 'JOSEPH HERMAN', value: 'JOSEPH HERMAN' },
  { id: 'JOSHUA DRAPER', value: 'JOSHUA DRAPER' },
  { id: 'JOSLYN PILLING', value: 'JOSLYN PILLING' },
  { id: 'JUSTIN SCHELIN', value: 'JUSTIN SCHELIN' },
  { id: 'KATIE BENNETT', value: 'KATIE BENNETT' },
  { id: 'KATIE CARVER', value: 'KATIE CARVER' },
  { id: 'KAYE HOUSTON', value: 'KAYE HOUSTON' },
  { id: 'KEN KELLER', value: 'KEN KELLER' },
  { id: 'KEVIN HIZER', value: 'KEVIN HIZER' },
  { id: 'KILEY D WILLIS', value: 'KILEY D WILLIS' },
  { id: 'KIRK LAMBERT', value: 'KIRK LAMBERT' },
  { id: 'KODY FLOYD', value: 'KODY FLOYD' },
  { id: 'LUKE LASSITER', value: 'LUKE LASSITER' },
  { id: 'MARK COLBY', value: 'MARK COLBY' },
  { id: 'MICHAEL ADAM', value: 'MICHAEL ADAM' },
  { id: 'MICHAEL RENCKERT', value: 'MICHAEL RENCKERT' },
  { id: 'MITCHELL CARVER', value: 'MITCHELL CARVER' },
  { id: 'NATHAN ELDRIDGE', value: 'NATHAN ELDRIDGE' },
  { id: 'NOT SUPERVISED', value: 'NOT SUPERVISED' },
  { id: 'RANDI CARTER', value: 'RANDI CARTER' },
  { id: 'RICHARD GLEN MORRIS', value: 'RICHARD GLEN MORRIS' },
  { id: 'RICHARD JENKINS', value: 'RICHARD JENKINS' },
  { id: 'RICK SMITH', value: 'RICK SMITH' },
  { id: 'ROBERT CID', value: 'ROBERT CID' },
  { id: 'RUBEN CERVANTES', value: 'RUBEN CERVANTES' },
  { id: 'RYAN PROCTOR', value: 'RYAN PROCTOR' },
  { id: 'SCOTT C. STEPHENS', value: 'SCOTT C. STEPHENS' },
  { id: 'SETH ROBINSON', value: 'SETH ROBINSON' },
  { id: 'SIMON K FULLER', value: 'SIMON K FULLER' },
  { id: 'STEVE WILLIAMSON', value: 'STEVE WILLIAMSON' },
  { id: 'STEVE YEATES', value: 'STEVE YEATES' },
  { id: 'TANYA DIANA', value: 'TANYA DIANA' },
  { id: 'TERRY BANKS', value: 'TERRY BANKS' },
  { id: 'TODD GRAHAM', value: 'TODD GRAHAM' },
  { id: 'TONY GARRETT', value: 'TONY GARRETT' },
  { id: 'TRACY SHOCK', value: 'TRACY SHOCK' },
  { id: 'VIDA BETTS', value: 'VIDA BETTS' },
  { id: 'WADE ALLINSON', value: 'WADE ALLINSON' },
  { id: 'WILLIAM LUKE', value: 'WILLIAM LUKE' },
  { id: 'WILLIAM MORELL', value: 'WILLIAM MORELL' },
];

const supervisionContactDays = [30, 60, 90, 180];

const counties = [
  'BEAVER',
  'BOX ELDER',
  'CACHE',
  'CARBON',
  'DAGGETT',
  'DAVIS',
  'DUCHESNE',
  'EMERY',
  'GARFIELD',
  'GRAND',
  'IRON',
  'JUAB',
  'KANE',
  'MILLARD',
  'MORGAN',
  'PIUTE',
  'RICH',
  'SALT LAKE',
  'SAN JUAN',
  'SANPETE',
  'SEVIER',
  'SUMMIT',
  'TOOELE',
  'UINTAH',
  'UTAH',
  'WASATCH',
  'WASHINGTON',
  'WAYNE',
  'WEBER',
];

export { supervisionItems, mainGangs, offenseTypes, agentLookup, supervisorLookup, supervisionContactDays, counties };
