const supervisionItems = [
  {
    name: 'CCC',
    id: 'ccc',
  },
  {
    name: 'PVP',
    id: 'pvp',
  },
  {
    name: 'COMP',
    id: 'comp',
  },
  {
    name: 'DEP',
    id: 'dep',
  },
  {
    name: 'EM',
    id: 'em',
  },
  {
    name: 'GPS',
    id: 'gps',
  },
  {
    name: 'SO',
    id: 'so',
  },
  {
    name: 'SO-A',
    id: 'soa',
  },
  {
    name: 'SO-B',
    id: 'sob',
  },
  {
    name: 'SO-C',
    id: 'soc',
  },
  {
    name: 'FUG',
    id: 'fug',
  },
  {
    name: 'INCAR',
    id: 'incar',
  },
  {
    name: 'RESID',
    id: 'resid',
  },
  {
    name: 'DRUG CT',
    id: 'drugct',
  },
  {
    name: 'DORA',
    id: 'dora',
  },
  {
    name: 'ECR',
    id: 'ecr',
  },
  {
    name: 'FOSI',
    id: 'fosi',
  },
  {
    name: 'IG INT',
    id: 'igint',
  },
  {
    name: 'MIO',
    id: 'mio',
  },
];

const mainGangs = [
  {
    name: 'sureno',
    id: 'sureno',
  },
  {
    name: 'nortenos',
    id: 'nortenos',
  },
  {
    name: 'omg - outlaw motorcycl',
    id: 'omg',
  },
  {
    name: 'white supremacist',
    id: 'ws',
  },
  {
    name: 'crip',
    id: 'crip',
  },
  {
    name: 'bloods',
    id: 'blood',
  },
  {
    name: 'people nation',
    id: 'pn',
  },
  {
    name: 'folk nation',
    id: 'fn',
  },
  {
    name: 'others',
    id: 'o',
  },
  {
    name: 'no type specified',
    id: 'none',
  },
  {
    name: 'vlt',
    id: 'vlt',
  },
  {
    name: 'o13',
    id: '13',
  },
  {
    name: 'qvo',
    id: 'qvo',
  },
];

const offenseTypes = [
  {
    name: 'murder',
    id: 'A',
  },
  {
    name: 'sex/registerable',
    id: 'D',
  },
  {
    name: 'sex/non-registerable',
    id: 'E',
  },
  {
    name: 'person',
    id: 'G',
  },
  {
    name: 'alcohol & drug',
    id: 'J',
  },
  {
    name: 'property',
    id: 'M',
  },
  {
    name: 'weapons',
    id: 'P',
  },
  {
    name: 'driving',
    id: 'S',
  },
  {
    name: 'other',
    id: 'V',
  },
  {
    name: 'drug possession only',
    id: 'X',
  },
  {
    name: 'unknown',
    id: 'Z',
  },
];

const agentLookup = [
  { id: '176268', value: 'AARON LEE', agent_Id: 'alee2', supervisor_Id: 'klambert', supervisor: 'KIRK LAMBERT' },
  { id: '112112', value: 'BLAINE BILLS', agent_Id: 'bbills', supervisor_Id: 'klambert', supervisor: 'KIRK LAMBERT' },
  { id: '181717', value: 'BRYAN JOHNSON', agent_Id: 'bjohns11', supervisor_Id: 'klambert', supervisor: 'KIRK LAMBERT' },
  { id: '200783', value: 'CRYSTAL BLASI', agent_Id: 'ccblasi', supervisor_Id: 'klambert', supervisor: 'KIRK LAMBERT' },
  { id: '207962', value: 'DENTON CALL', agent_Id: 'dcall', supervisor_Id: 'klambert', supervisor: 'KIRK LAMBERT' },
  {
    id: '152917',
    value: 'JONATHAN REYNOLDS',
    agent_Id: 'jreynold',
    supervisor_Id: 'klambert',
    supervisor: 'KIRK LAMBERT',
  },
  { id: '161009', value: 'KODY MERRITT', agent_Id: 'kmerritt', supervisor_Id: 'klambert', supervisor: 'KIRK LAMBERT' },
  { id: '205182', value: 'AARON POWELL', agent_Id: 'apowell', supervisor_Id: 'vbetts', supervisor: 'VIDA BETTS' },
  { id: '209290', value: 'BLAKE GREENHALGH', agent_Id: 'bgreenha', supervisor_Id: 'vbetts', supervisor: 'VIDA BETTS' },
  { id: '209203', value: 'BRI SACKETT', agent_Id: 'brisacke', supervisor_Id: 'vbetts', supervisor: 'VIDA BETTS' },
  { id: '154990', value: 'CHERYL FRANDSEN', agent_Id: 'cmfrands', supervisor_Id: 'vbetts', supervisor: 'VIDA BETTS' },
  { id: '211306', value: 'DUSTIN ANDERSON', agent_Id: 'dlanders', supervisor_Id: 'vbetts', supervisor: 'VIDA BETTS' },
  { id: '223502', value: 'HERBERT TODACHINNIE', agent_Id: 'htodachi', supervisor_Id: 'vbetts', supervisor: 'VIDA BETTS' },
  { id: '112150', value: 'JAMES WEAVER', agent_Id: 'jweaver', supervisor_Id: 'vbetts', supervisor: 'VIDA BETTS' },
  { id: '211299', value: 'JANECA KLAYKO', agent_Id: 'jklayko', supervisor_Id: 'vbetts', supervisor: 'VIDA BETTS' },
  { id: '186609', value: 'JOHN POWELL', agent_Id: 'jdpowell', supervisor_Id: 'vbetts', supervisor: 'VIDA BETTS' },
  { id: '153535', value: 'JOHNATHAN VASQUEZ', agent_Id: 'jvasquez', supervisor_Id: 'vbetts', supervisor: 'VIDA BETTS' },
  { id: '150617', value: 'JOSEPH F. LANEY', agent_Id: 'jlaney', supervisor_Id: 'vbetts', supervisor: 'VIDA BETTS' },
  { id: '176103', value: 'KYLA BUNNELL', agent_Id: 'kbunnell', supervisor_Id: 'vbetts', supervisor: 'VIDA BETTS' },
  { id: '221345', value: 'NICKOLAS PARKER', agent_Id: 'ndparker', supervisor_Id: 'vbetts', supervisor: 'VIDA BETTS' },
  { id: '153266', value: 'STEPHEN REGRUTO', agent_Id: 'sregruto', supervisor_Id: 'vbetts', supervisor: 'VIDA BETTS' },
  { id: '166086', value: 'AARON SMITH', agent_Id: 'asmith7', supervisor_Id: 'kwillis2', supervisor: 'KILEY D WILLIS' },
  { id: '201167', value: 'ARTURO DUARTE', agent_Id: 'aduarte', supervisor_Id: 'kwillis2', supervisor: 'KILEY D WILLIS' },
  { id: '210955', value: 'JEANNA BIRCH', agent_Id: 'jbirch', supervisor_Id: 'kwillis2', supervisor: 'KILEY D WILLIS' },
  {
    id: '176272',
    value: 'JEFFREY HANSEN',
    agent_Id: 'jeffghan',
    supervisor_Id: 'kwillis2',
    supervisor: 'KILEY D WILLIS',
  },
  { id: '207613', value: 'ROGER CETINA', agent_Id: 'rcetina', supervisor_Id: 'kwillis2', supervisor: 'KILEY D WILLIS' },
  { id: '217010', value: 'ABRAM ALLRED', agent_Id: 'abramall', supervisor_Id: 'rsmith4', supervisor: 'RICK SMITH' },
  { id: '159777', value: 'CHRISTINE STRONG', agent_Id: 'cstrong', supervisor_Id: 'rsmith4', supervisor: 'RICK SMITH' },
  { id: '159177', value: 'JEFFREY ROWLEY', agent_Id: 'jrowley', supervisor_Id: 'rsmith4', supervisor: 'RICK SMITH' },
  { id: '207017', value: 'JORDAN BURGESS', agent_Id: 'jburgess', supervisor_Id: 'rsmith4', supervisor: 'RICK SMITH' },
  { id: '214125', value: 'KATHRYN SUTORIUS', agent_Id: 'ksutorio', supervisor_Id: 'rsmith4', supervisor: 'RICK SMITH' },
  { id: '194516', value: 'NICK SMITH', agent_Id: 'nsmith4', supervisor_Id: 'rsmith4', supervisor: 'RICK SMITH' },
  { id: '173024', value: 'SITH KIM', agent_Id: 'skim', supervisor_Id: 'rsmith4', supervisor: 'RICK SMITH' },
  { id: '169801', value: 'ADAM CHARD', agent_Id: 'achard', supervisor_Id: 'jshardlo', supervisor: 'JEFF SHARDLOW' },
  { id: '193619', value: 'CHAD BOWLER', agent_Id: 'cbowler', supervisor_Id: 'jshardlo', supervisor: 'JEFF SHARDLOW' },
  {
    id: '211821',
    value: 'DERRIS PETERSON',
    agent_Id: 'derrispe',
    supervisor_Id: 'jshardlo',
    supervisor: 'JEFF SHARDLOW',
  },
  { id: '186662', value: 'NICHOLAS STRONG', agent_Id: 'nstrong', supervisor_Id: 'jshardlo', supervisor: 'JEFF SHARDLOW' },
  { id: '164046', value: 'PAUL GRAY', agent_Id: 'pgray2', supervisor_Id: 'jshardlo', supervisor: 'JEFF SHARDLOW' },
  { id: '130474', value: 'RICK SMITH', agent_Id: 'rsmith4', supervisor_Id: 'jshardlo', supervisor: 'JEFF SHARDLOW' },
  { id: '146301', value: 'ROBERT CID', agent_Id: 'rcid', supervisor_Id: 'jshardlo', supervisor: 'JEFF SHARDLOW' },
  { id: '197500', value: 'STEVE HATCH', agent_Id: 'stevehat', supervisor_Id: 'jshardlo', supervisor: 'JEFF SHARDLOW' },
  { id: '159762', value: 'TODD HILLIKER', agent_Id: 'thillike', supervisor_Id: 'jshardlo', supervisor: 'JEFF SHARDLOW' },
  { id: '220104', value: 'AIDEN BIRD', agent_Id: 'aidenbir', supervisor_Id: 'aqrobert', supervisor: 'AUSTIN Q ROBERTS' },
  { id: '194508', value: 'DEREK HOLMES', agent_Id: 'dholmes', supervisor_Id: 'aqrobert', supervisor: 'AUSTIN Q ROBERTS' },
  { id: '147141', value: 'DORI GRANGE', agent_Id: 'dgrange', supervisor_Id: 'aqrobert', supervisor: 'AUSTIN Q ROBERTS' },
  {
    id: '214121',
    value: 'MICHAEL PETERSEN',
    agent_Id: 'mwpeters',
    supervisor_Id: 'aqrobert',
    supervisor: 'AUSTIN Q ROBERTS',
  },
  { id: '217451', value: 'ALAN GREENWOOD', agent_Id: 'agreenwo', supervisor_Id: 'gsmith2', supervisor: 'GREG SMITH' },
  { id: '211792', value: 'ASHLEY POWELL', agent_Id: 'ampowell', supervisor_Id: 'gsmith2', supervisor: 'GREG SMITH' },
  { id: '184234', value: 'BOB CHASTAIN', agent_Id: 'bchastai', supervisor_Id: 'gsmith2', supervisor: 'GREG SMITH' },
  { id: '176276', value: 'JERRY AARON', agent_Id: 'jaaron', supervisor_Id: 'gsmith2', supervisor: 'GREG SMITH' },
  { id: '197706', value: 'KEVIN D CLAUNCH', agent_Id: 'kclaunch', supervisor_Id: 'gsmith2', supervisor: 'GREG SMITH' },
  { id: '198990', value: 'STEVEN UNSWORTH', agent_Id: 'srunswor', supervisor_Id: 'gsmith2', supervisor: 'GREG SMITH' },
  { id: '207993', value: 'TROY THOMPSON', agent_Id: 'troythom', supervisor_Id: 'gsmith2', supervisor: 'GREG SMITH' },
  { id: '169692', value: 'ALEX ADAMSON', agent_Id: 'aadamson', supervisor_Id: 'dhanna2', supervisor: 'DAVID HANNA' },
  { id: '126878', value: 'ALFREDO GUILLEN', agent_Id: 'aguillen', supervisor_Id: 'dhanna2', supervisor: 'DAVID HANNA' },
  { id: '218159', value: 'ANDREW SCOTT', agent_Id: 'apscott', supervisor_Id: 'dhanna2', supervisor: 'DAVID HANNA' },
  { id: '154944', value: 'BRANDON PIXTON', agent_Id: 'bpixton', supervisor_Id: 'dhanna2', supervisor: 'DAVID HANNA' },
  { id: '221735', value: 'JON SESSIONS', agent_Id: 'jsession', supervisor_Id: 'dhanna2', supervisor: 'DAVID HANNA' },
  { id: '200041', value: 'KENNETH COX', agent_Id: 'kennethc', supervisor_Id: 'dhanna2', supervisor: 'DAVID HANNA' },
  { id: '181746', value: 'NEIL SMITH', agent_Id: 'nsmith3', supervisor_Id: 'dhanna2', supervisor: 'DAVID HANNA' },
  { id: '211791', value: 'ALEX HART', agent_Id: 'adhart', supervisor_Id: 'thillike', supervisor: 'TODD HILLIKER' },
  {
    id: '140653',
    value: 'CAMILLE M CHRISTENSEN',
    agent_Id: 'camillej',
    supervisor_Id: 'thillike',
    supervisor: 'TODD HILLIKER',
  },
  { id: '141676', value: 'JAMES LEGORE', agent_Id: 'jlegore', supervisor_Id: 'thillike', supervisor: 'TODD HILLIKER' },
  { id: '134467', value: 'JAY ROSS', agent_Id: 'jross', supervisor_Id: 'thillike', supervisor: 'TODD HILLIKER' },
  { id: '132346', value: 'RUPERT JACKSON', agent_Id: 'rjackson', supervisor_Id: 'thillike', supervisor: 'TODD HILLIKER' },
  { id: '181483', value: 'TRAVIS REPP', agent_Id: 'tarepp', supervisor_Id: 'thillike', supervisor: 'TODD HILLIKER' },
  { id: '198635', value: 'ALIE CARLSON', agent_Id: 'aliecarl', supervisor_Id: 'rjenkins', supervisor: 'RICHARD JENKINS' },
  {
    id: '134413',
    value: 'DANIEL JORGENSEN',
    agent_Id: 'djorgen2',
    supervisor_Id: 'rjenkins',
    supervisor: 'RICHARD JENKINS',
  },
  {
    id: '189791',
    value: 'JOHN B LIVINGSTON',
    agent_Id: 'jlivings',
    supervisor_Id: 'rjenkins',
    supervisor: 'RICHARD JENKINS',
  },
  {
    id: '164026',
    value: 'MATTHEW JENSEN',
    agent_Id: 'mjensen5',
    supervisor_Id: 'rjenkins',
    supervisor: 'RICHARD JENKINS',
  },
  { id: '192668', value: 'MORGAN R BOND', agent_Id: 'mbond', supervisor_Id: 'rjenkins', supervisor: 'RICHARD JENKINS' },
  {
    id: '189818',
    value: 'QUINN STICKNEY',
    agent_Id: 'qstickne',
    supervisor_Id: 'rjenkins',
    supervisor: 'RICHARD JENKINS',
  },
  { id: '160282', value: 'REGAN A RAY', agent_Id: 'rray', supervisor_Id: 'rjenkins', supervisor: 'RICHARD JENKINS' },
  { id: '182988', value: 'SHAWN CHURCH', agent_Id: 'schurch', supervisor_Id: 'rjenkins', supervisor: 'RICHARD JENKINS' },
  { id: '196382', value: 'ALLEN RUECKERT', agent_Id: 'allenrue', supervisor_Id: 'kfloyd', supervisor: 'KODY FLOYD' },
  { id: '201933', value: 'BRYCE ATKIN', agent_Id: 'batkin1', supervisor_Id: 'kfloyd', supervisor: 'KODY FLOYD' },
  { id: '197479', value: 'CHASE WITHERS', agent_Id: 'chasewit', supervisor_Id: 'kfloyd', supervisor: 'KODY FLOYD' },
  { id: '187199', value: 'CHRISTOPHER ASTLE', agent_Id: 'castle', supervisor_Id: 'kfloyd', supervisor: 'KODY FLOYD' },
  { id: '171952', value: 'COREY MCEWAN', agent_Id: 'cmcewan', supervisor_Id: 'kfloyd', supervisor: 'KODY FLOYD' },
  { id: '105873', value: 'JERRY COOK', agent_Id: 'jfcook', supervisor_Id: 'kfloyd', supervisor: 'KODY FLOYD' },
  { id: '187226', value: 'KELEPI VAEA', agent_Id: 'kvaea', supervisor_Id: 'kfloyd', supervisor: 'KODY FLOYD' },
  { id: '164677', value: 'ALYSA PETERSON', agent_Id: 'alysapet', supervisor_Id: 'rramsey', supervisor: 'ROSARIO RAMSEY' },
  {
    id: '117384',
    value: 'ALYSSA DAVENPORT',
    agent_Id: 'adavenpo',
    supervisor_Id: 'jgarrett',
    supervisor: 'JAMES GARRETT',
  },
  { id: '187276', value: 'BROC HUNTSMAN', agent_Id: 'bhuntsma', supervisor_Id: 'jgarrett', supervisor: 'JAMES GARRETT' },
  { id: '114442', value: 'DANIEL GORDON', agent_Id: 'dgordon3', supervisor_Id: 'jgarrett', supervisor: 'JAMES GARRETT' },
  { id: '154429', value: 'DAVID OWENS', agent_Id: 'dowens', supervisor_Id: 'jgarrett', supervisor: 'JAMES GARRETT' },
  { id: '192644', value: 'GARY P TIDWELL', agent_Id: 'garytidw', supervisor_Id: 'jgarrett', supervisor: 'JAMES GARRETT' },
  { id: '172447', value: 'IAN ADAMS', agent_Id: 'iadams2', supervisor_Id: 'jgarrett', supervisor: 'JAMES GARRETT' },
  { id: '188410', value: 'JADE ESPINOZA', agent_Id: 'jadesore', supervisor_Id: 'jgarrett', supervisor: 'JAMES GARRETT' },
  {
    id: '131920',
    value: 'JON KELLY MAXWELL',
    agent_Id: 'jmaxwell',
    supervisor_Id: 'jgarrett',
    supervisor: 'JAMES GARRETT',
  },
  {
    id: '220832',
    value: 'ALYSSA HACKBARTH',
    agent_Id: 'ajhackba',
    supervisor_Id: 'jpilling',
    supervisor: 'JOSLYN PILLING',
  },
  {
    id: '212840',
    value: 'BERNADETTE DEFISHER',
    agent_Id: 'bdefishe',
    supervisor_Id: 'jpilling',
    supervisor: 'JOSLYN PILLING',
  },
  {
    id: '204550',
    value: 'GALIT LEVANON-ARELLANO',
    agent_Id: 'galit',
    supervisor_Id: 'jpilling',
    supervisor: 'JOSLYN PILLING',
  },
  { id: '148686', value: 'KRISTA HOOKS', agent_Id: 'kristaho', supervisor_Id: 'jpilling', supervisor: 'JOSLYN PILLING' },
  { id: '114306', value: 'MULIAINGA LATU', agent_Id: 'mlatu', supervisor_Id: 'jpilling', supervisor: 'JOSLYN PILLING' },
  {
    id: '182311',
    value: 'NOELIA CASTILLO',
    agent_Id: 'noeliac',
    supervisor_Id: 'jpilling',
    supervisor: 'JOSLYN PILLING',
  },
  { id: '219698', value: 'SHANNON ILIEV', agent_Id: 'siliev', supervisor_Id: 'jpilling', supervisor: 'JOSLYN PILLING' },
  { id: '138127', value: 'TIFFANY LEES', agent_Id: 'tlees', supervisor_Id: 'jpilling', supervisor: 'JOSLYN PILLING' },
  {
    id: '169976',
    value: 'AMANDA THEOBALD',
    agent_Id: 'amandath',
    supervisor_Id: 'adressle',
    supervisor: 'ALAN DRESSLER',
  },
  {
    id: '181817',
    value: 'AUSTIN KENNINGTON',
    agent_Id: 'akenning',
    supervisor_Id: 'adressle',
    supervisor: 'ALAN DRESSLER',
  },
  { id: '152635', value: 'JUSTIN SCHELIN', agent_Id: 'jscheli2', supervisor_Id: 'adressle', supervisor: 'ALAN DRESSLER' },
  { id: '121985', value: 'LEIONI IKA', agent_Id: 'lika', supervisor_Id: 'adressle', supervisor: 'ALAN DRESSLER' },
  { id: '162950', value: 'PAUL DOLGNER', agent_Id: 'pdolgner', supervisor_Id: 'adressle', supervisor: 'ALAN DRESSLER' },
  { id: '203137', value: 'AMBER GARDNER', agent_Id: 'algardne', supervisor_Id: 'jbranin', supervisor: 'JENNIFER BRANIN' },
  {
    id: '175297',
    value: 'JAMIE R TURRUBIARTEZ',
    agent_Id: 'jrames',
    supervisor_Id: 'jbranin',
    supervisor: 'JENNIFER BRANIN',
  },
  {
    id: '160307',
    value: 'MICHAEL CLARENCE ROBINSON',
    agent_Id: 'mrobinso',
    supervisor_Id: 'jbranin',
    supervisor: 'JENNIFER BRANIN',
  },
  {
    id: '207343',
    value: 'AMBER MILLER',
    agent_Id: 'amiller1',
    supervisor_Id: 'gercanbr',
    supervisor: 'GLENN ERCANBRACK',
  },
  {
    id: '120782',
    value: 'AMMON JONES',
    agent_Id: 'ammonjon',
    supervisor_Id: 'cgunders',
    supervisor: 'CATHERINE GUNDERSON',
  },
  {
    id: '134900',
    value: 'BRIAN SMITH',
    agent_Id: 'bssmith',
    supervisor_Id: 'cgunders',
    supervisor: 'CATHERINE GUNDERSON',
  },
  {
    id: '208006',
    value: 'CLIFF HAMILTON',
    agent_Id: 'cfhamilt',
    supervisor_Id: 'cgunders',
    supervisor: 'CATHERINE GUNDERSON',
  },
  {
    id: '208455',
    value: 'GREG OWENS',
    agent_Id: 'gsowens',
    supervisor_Id: 'cgunders',
    supervisor: 'CATHERINE GUNDERSON',
  },
  {
    id: '214812',
    value: 'MATTHEW NANCE',
    agent_Id: 'mnance',
    supervisor_Id: 'cgunders',
    supervisor: 'CATHERINE GUNDERSON',
  },
  {
    id: '147619',
    value: 'TERESA OSBORN',
    agent_Id: 'tosborn',
    supervisor_Id: 'cgunders',
    supervisor: 'CATHERINE GUNDERSON',
  },
  {
    id: '221410',
    value: 'TYLER YOUNG',
    agent_Id: 'tjyoung',
    supervisor_Id: 'cgunders',
    supervisor: 'CATHERINE GUNDERSON',
  },
  { id: '182708', value: 'ANA M MASCIANTONIO', agent_Id: 'amascian', supervisor_Id: 'madam', supervisor: 'MICHAEL ADAM' },
  { id: '202359', value: 'KELLY ALLEN', agent_Id: 'kallen1', supervisor_Id: 'madam', supervisor: 'MICHAEL ADAM' },
  { id: '183492', value: 'KYLE CELAURO', agent_Id: 'kcelauro', supervisor_Id: 'madam', supervisor: 'MICHAEL ADAM' },
  { id: '197556', value: 'MISTY DALTON', agent_Id: 'mmoyes', supervisor_Id: 'madam', supervisor: 'MICHAEL ADAM' },
  { id: '207793', value: 'SPENCER DRAKE', agent_Id: 'sdrake', supervisor_Id: 'madam', supervisor: 'MICHAEL ADAM' },
  { id: '214120', value: 'TRACE PAUL', agent_Id: 'tracepau', supervisor_Id: 'madam', supervisor: 'MICHAEL ADAM' },
  { id: '211209', value: 'TRINA WHITEHEAD', agent_Id: 'twhitehe', supervisor_Id: 'madam', supervisor: 'MICHAEL ADAM' },
  { id: '204196', value: 'TYSON KOMER', agent_Id: 'tkomer', supervisor_Id: 'madam', supervisor: 'MICHAEL ADAM' },
  { id: '196368', value: 'ANDREW DALTON', agent_Id: 'andrewda', supervisor_Id: 'jcampos', supervisor: 'JAMES CAMPOS' },
  { id: '132917', value: 'JEROMY SAMPSON', agent_Id: 'jsampson', supervisor_Id: 'jcampos', supervisor: 'JAMES CAMPOS' },
  { id: '213012', value: 'MICHAEL CRANE', agent_Id: 'mccrane', supervisor_Id: 'jcampos', supervisor: 'JAMES CAMPOS' },
  { id: '213437', value: 'NICOLAS SHOBE', agent_Id: 'nshobe', supervisor_Id: 'jcampos', supervisor: 'JAMES CAMPOS' },
  { id: '208538', value: 'WAYNE SMITH', agent_Id: 'wmsmith', supervisor_Id: 'jcampos', supervisor: 'JAMES CAMPOS' },
  {
    id: '222826',
    value: 'ANDREW HAMILTON',
    agent_Id: 'andrewha',
    supervisor_Id: 'swilliam',
    supervisor: 'STEVE WILLIAMSON',
  },
  { id: '200038', value: 'BLAKE QUAYLE', agent_Id: 'bquayle', supervisor_Id: 'swilliam', supervisor: 'STEVE WILLIAMSON' },
  { id: '192637', value: 'CHAD NICHOL', agent_Id: 'chadnich', supervisor_Id: 'swilliam', supervisor: 'STEVE WILLIAMSON' },
  { id: '221144', value: 'CHERI DEAN', agent_Id: 'cldean', supervisor_Id: 'swilliam', supervisor: 'STEVE WILLIAMSON' },
  { id: '166475', value: 'EMIKO CRANE', agent_Id: 'ecrane', supervisor_Id: 'swilliam', supervisor: 'STEVE WILLIAMSON' },
  { id: '188497', value: 'MAJOR HENRY', agent_Id: 'mhenry', supervisor_Id: 'swilliam', supervisor: 'STEVE WILLIAMSON' },
  { id: '161042', value: 'NICHOLAS PEAY', agent_Id: 'npeay', supervisor_Id: 'swilliam', supervisor: 'STEVE WILLIAMSON' },
  {
    id: '193632',
    value: 'NICK BUNNELL',
    agent_Id: 'nbunnell',
    supervisor_Id: 'swilliam',
    supervisor: 'STEVE WILLIAMSON',
  },
  {
    id: '226310',
    value: 'STEPHANIE PARRISH',
    agent_Id: 'sparrish',
    supervisor_Id: 'swilliam',
    supervisor: 'STEVE WILLIAMSON',
  },
  { id: '198661', value: 'ANDREW HAMPTON', agent_Id: 'ahampton', supervisor_Id: 'tjindra', supervisor: 'THOMAS JINDRA' },
  { id: '182981', value: 'AUSTIN BRACKEN', agent_Id: 'abracken', supervisor_Id: 'tjindra', supervisor: 'THOMAS JINDRA' },
  { id: '213292', value: 'CASEY CLAWSON', agent_Id: 'cclawson', supervisor_Id: 'tjindra', supervisor: 'THOMAS JINDRA' },
  { id: '166498', value: 'DAVID GAFFNEY', agent_Id: 'dgaffney', supervisor_Id: 'tjindra', supervisor: 'THOMAS JINDRA' },
  { id: '187762', value: 'DEON WALSER', agent_Id: 'dwalser', supervisor_Id: 'tjindra', supervisor: 'THOMAS JINDRA' },
  { id: '168608', value: 'JASON ROOTHOFF', agent_Id: 'jroothof', supervisor_Id: 'tjindra', supervisor: 'THOMAS JINDRA' },
  { id: '204848', value: 'JEFF BUCK', agent_Id: 'jbuck', supervisor_Id: 'tjindra', supervisor: 'THOMAS JINDRA' },
  { id: '115625', value: 'STERLING BARTON', agent_Id: 'sbarton', supervisor_Id: 'tjindra', supervisor: 'THOMAS JINDRA' },
  { id: '181736', value: 'STEVEN BAKER', agent_Id: 'sbaker', supervisor_Id: 'tjindra', supervisor: 'THOMAS JINDRA' },
  { id: '155396', value: 'STEVEN OSTLER', agent_Id: 'sostler', supervisor_Id: 'tjindra', supervisor: 'THOMAS JINDRA' },
  { id: '196360', value: 'ANDREW WALKER', agent_Id: 'awalker1', supervisor_Id: 'ccueva', supervisor: 'CLAUDIO B CUEVA' },
  {
    id: '191429',
    value: 'BRANDON W MEADOWS',
    agent_Id: 'bmeadows',
    supervisor_Id: 'ccueva',
    supervisor: 'CLAUDIO B CUEVA',
  },
  { id: '174820', value: 'BRENDAN NISSEN', agent_Id: 'bnissen', supervisor_Id: 'ccueva', supervisor: 'CLAUDIO B CUEVA' },
  {
    id: '167690',
    value: 'CHARLES CHAPPELL',
    agent_Id: 'cchappel',
    supervisor_Id: 'ccueva',
    supervisor: 'CLAUDIO B CUEVA',
  },
  { id: '196358', value: 'DEVIN TOLTON', agent_Id: 'devintol', supervisor_Id: 'ccueva', supervisor: 'CLAUDIO B CUEVA' },
  {
    id: '202347',
    value: 'RUSSELL ONTIVEROS',
    agent_Id: 'russello',
    supervisor_Id: 'ccueva',
    supervisor: 'CLAUDIO B CUEVA',
  },
  { id: '199952', value: 'TILER HEINEY', agent_Id: 'theiney', supervisor_Id: 'ccueva', supervisor: 'CLAUDIO B CUEVA' },
  { id: '195418', value: 'ZACH LAYCOCK', agent_Id: 'zlaycock', supervisor_Id: 'ccueva', supervisor: 'CLAUDIO B CUEVA' },
  {
    id: '120606',
    value: 'ANTOINETTE AIONO',
    agent_Id: 'aaiono',
    supervisor_Id: 'jnichole',
    supervisor: 'JASON NICHOLES',
  },
  { id: '176016', value: 'DAVID HANNA', agent_Id: 'dhanna2', supervisor_Id: 'jnichole', supervisor: 'JASON NICHOLES' },
  { id: '183001', value: 'JOSEPH HERMAN', agent_Id: 'jherman3', supervisor_Id: 'jnichole', supervisor: 'JASON NICHOLES' },
  {
    id: '147960',
    value: 'KILEY D WILLIS',
    agent_Id: 'kwillis2',
    supervisor_Id: 'jnichole',
    supervisor: 'JASON NICHOLES',
  },
  {
    id: '154417',
    value: 'ASHLEIGH JOHNSTON',
    agent_Id: 'ajohnst2',
    supervisor_Id: 'rmorris',
    supervisor: 'RICHARD GLEN MORRIS',
  },
  {
    id: '198358',
    value: 'BRADY BARNEY',
    agent_Id: 'bbarney',
    supervisor_Id: 'rmorris',
    supervisor: 'RICHARD GLEN MORRIS',
  },
  {
    id: '212294',
    value: 'JAY SISSENER',
    agent_Id: 'jsissene',
    supervisor_Id: 'rmorris',
    supervisor: 'RICHARD GLEN MORRIS',
  },
  {
    id: '207816',
    value: 'MATTHEW HARDING',
    agent_Id: 'mharding',
    supervisor_Id: 'rmorris',
    supervisor: 'RICHARD GLEN MORRIS',
  },
  {
    id: '205445',
    value: 'SHAWN COSTON',
    agent_Id: 'scoston',
    supervisor_Id: 'rmorris',
    supervisor: 'RICHARD GLEN MORRIS',
  },
  {
    id: '206076',
    value: 'SPENCER MEMMOTT',
    agent_Id: 'smemmott',
    supervisor_Id: 'rmorris',
    supervisor: 'RICHARD GLEN MORRIS',
  },
  { id: '158655', value: 'AUDREY BROWN', agent_Id: 'axbrown', supervisor_Id: 'jfairban', supervisor: 'JASON FAIRBANKS' },
  {
    id: '210308',
    value: 'BLAKE SESSIONS',
    agent_Id: 'bsession',
    supervisor_Id: 'jfairban',
    supervisor: 'JASON FAIRBANKS',
  },
  { id: '192689', value: 'BRAD D LUND', agent_Id: 'bradlund', supervisor_Id: 'jfairban', supervisor: 'JASON FAIRBANKS' },
  { id: '164329', value: 'DAVID JENSEN', agent_Id: 'djensen3', supervisor_Id: 'jfairban', supervisor: 'JASON FAIRBANKS' },
  { id: '210942', value: 'JARON TAYLOR', agent_Id: 'jarontay', supervisor_Id: 'jfairban', supervisor: 'JASON FAIRBANKS' },
  {
    id: '155411',
    value: 'JESS A. PLOUZEK',
    agent_Id: 'jplouzek',
    supervisor_Id: 'jfairban',
    supervisor: 'JASON FAIRBANKS',
  },
  {
    id: '178146',
    value: 'KEIRA THEETGE',
    agent_Id: 'ktheetge',
    supervisor_Id: 'jfairban',
    supervisor: 'JASON FAIRBANKS',
  },
  {
    id: '151894',
    value: 'SHANALEE ROLFSON',
    agent_Id: 'srolfson',
    supervisor_Id: 'jfairban',
    supervisor: 'JASON FAIRBANKS',
  },
  {
    id: '153794',
    value: 'SHAWN FETTERS',
    agent_Id: 'sfetters',
    supervisor_Id: 'jfairban',
    supervisor: 'JASON FAIRBANKS',
  },
  {
    id: '163423',
    value: 'SHAWN SCHIPPERS',
    agent_Id: 'sschippe',
    supervisor_Id: 'jfairban',
    supervisor: 'JASON FAIRBANKS',
  },
  {
    id: '191938',
    value: 'STEPHEN DOROCIAK',
    agent_Id: 'sdorocia',
    supervisor_Id: 'jfairban',
    supervisor: 'JASON FAIRBANKS',
  },
  { id: '205233', value: 'TY AMY', agent_Id: 'tyamy', supervisor_Id: 'jfairban', supervisor: 'JASON FAIRBANKS' },
  { id: '106821', value: 'BARRY HANSEN', agent_Id: 'barryhan', supervisor_Id: 'mcarver', supervisor: 'MITCHELL CARVER' },
  {
    id: '130935',
    value: 'CANDACE DOMINGO',
    agent_Id: 'cdomingo',
    supervisor_Id: 'mcarver',
    supervisor: 'MITCHELL CARVER',
  },
  {
    id: '171499',
    value: 'CHRISTINA BRANDOM',
    agent_Id: 'cbrandom',
    supervisor_Id: 'mcarver',
    supervisor: 'MITCHELL CARVER',
  },
  { id: '199016', value: 'ILEANA ROSE', agent_Id: 'ipendley', supervisor_Id: 'mcarver', supervisor: 'MITCHELL CARVER' },
  {
    id: '158605',
    value: 'JASON KENNARD WILCOCK',
    agent_Id: 'jwilcock',
    supervisor_Id: 'mcarver',
    supervisor: 'MITCHELL CARVER',
  },
  { id: '115615', value: 'JENNIFER PAYNE', agent_Id: 'jpayne2', supervisor_Id: 'mcarver', supervisor: 'MITCHELL CARVER' },
  { id: '212889', value: 'JULIA LOLOFIE', agent_Id: 'jlolofie', supervisor_Id: 'mcarver', supervisor: 'MITCHELL CARVER' },
  { id: '106070', value: 'TRENT WYNN', agent_Id: 'twynn', supervisor_Id: 'mcarver', supervisor: 'MITCHELL CARVER' },
  { id: '155449', value: 'BART WOOLLEY', agent_Id: 'bartwo', supervisor_Id: 'sstephen', supervisor: 'SCOTT C. STEPHENS' },
  { id: '190140', value: 'CAMRYN WARD', agent_Id: 'camrynw', supervisor_Id: 'sstephen', supervisor: 'SCOTT C. STEPHENS' },
  {
    id: '203019',
    value: 'ELIANI SAMANIEGO',
    agent_Id: 'esamanie',
    supervisor_Id: 'sstephen',
    supervisor: 'SCOTT C. STEPHENS',
  },
  {
    id: '209260',
    value: 'JAKE HARWARD',
    agent_Id: 'jdharwar',
    supervisor_Id: 'sstephen',
    supervisor: 'SCOTT C. STEPHENS',
  },
  {
    id: '107260',
    value: 'SHANNON TEBBEN',
    agent_Id: 'smtebben',
    supervisor_Id: 'sstephen',
    supervisor: 'SCOTT C. STEPHENS',
  },
  { id: '164036', value: 'BEAU BROMLEY', agent_Id: 'bbromley', supervisor_Id: 'aaiono', supervisor: 'ANTOINETTE AIONO' },
  {
    id: '204120',
    value: 'JOEL ARMENDARIZ',
    agent_Id: 'jarmend',
    supervisor_Id: 'aaiono',
    supervisor: 'ANTOINETTE AIONO',
  },
  { id: '195436', value: 'KARL NORTH', agent_Id: 'knorth', supervisor_Id: 'aaiono', supervisor: 'ANTOINETTE AIONO' },
  { id: '173038', value: 'MATT HAUN', agent_Id: 'mhaun', supervisor_Id: 'aaiono', supervisor: 'ANTOINETTE AIONO' },
  { id: '205420', value: 'BEN BROADBENT', agent_Id: 'bbroadbe', supervisor_Id: 'ehamelin', supervisor: 'ELDON HAMELIN' },
  { id: '114063', value: 'BRAD DRAPER', agent_Id: 'bdraper', supervisor_Id: 'ehamelin', supervisor: 'ELDON HAMELIN' },
  { id: '215213', value: 'BRYANT COOK', agent_Id: 'bryantco', supervisor_Id: 'ehamelin', supervisor: 'ELDON HAMELIN' },
  { id: '212432', value: 'ETHAN REYNOLDS', agent_Id: 'ereynold', supervisor_Id: 'ehamelin', supervisor: 'ELDON HAMELIN' },
  { id: '202903', value: 'JUANITA BOREN', agent_Id: 'jboren', supervisor_Id: 'ehamelin', supervisor: 'ELDON HAMELIN' },
  { id: '127618', value: 'RICK COIL', agent_Id: 'rcoil', supervisor_Id: 'ehamelin', supervisor: 'ELDON HAMELIN' },
  { id: '104656', value: 'SHERRIE BROKAW', agent_Id: 'sbrokaw', supervisor_Id: 'ehamelin', supervisor: 'ELDON HAMELIN' },
  { id: '153800', value: 'BEN LASSITER', agent_Id: 'blassite', supervisor_Id: 'mcolby', supervisor: 'MARK COLBY' },
  { id: '140188', value: 'EDWARD SIMMONS', agent_Id: 'esimmons', supervisor_Id: 'mcolby', supervisor: 'MARK COLBY' },
  { id: '188426', value: 'ERIC S JACOBSON', agent_Id: 'ejacobso', supervisor_Id: 'mcolby', supervisor: 'MARK COLBY' },
  { id: '187198', value: 'GREGORY APGOOD', agent_Id: 'gapgood', supervisor_Id: 'mcolby', supervisor: 'MARK COLBY' },
  { id: '150794', value: 'JENNIFER M. MURRAY', agent_Id: 'jmurray2', supervisor_Id: 'mcolby', supervisor: 'MARK COLBY' },
  { id: '142750', value: 'KELLY GARDNER', agent_Id: 'kgardner', supervisor_Id: 'mcolby', supervisor: 'MARK COLBY' },
  { id: '128455', value: 'BEN ROWLEY', agent_Id: 'browley', supervisor_Id: 'salton', supervisor: 'SHAWN ALTON' },
  { id: '196145', value: 'BRITTANY SULLIVAN', agent_Id: 'brsulliv', supervisor_Id: 'salton', supervisor: 'SHAWN ALTON' },
  { id: '144439', value: 'DUSTIN R. VEATER', agent_Id: 'dveater', supervisor_Id: 'salton', supervisor: 'SHAWN ALTON' },
  { id: '162492', value: 'JOHN M AMES', agent_Id: 'james', supervisor_Id: 'salton', supervisor: 'SHAWN ALTON' },
  { id: '160272', value: 'SIERRA SCHILLING', agent_Id: 'sschilli', supervisor_Id: 'salton', supervisor: 'SHAWN ALTON' },
  { id: '219909', value: 'TYSON BARNEY', agent_Id: 'trbarney', supervisor_Id: 'salton', supervisor: 'SHAWN ALTON' },
  { id: '151257', value: 'BLAKE C HUNSAKER', agent_Id: 'bhunsake', supervisor_Id: 'talona', supervisor: 'TALONA TALBOT' },
  {
    id: '154043',
    value: 'BRANDON WOFFINDEN',
    agent_Id: 'bwoffind',
    supervisor_Id: 'talona',
    supervisor: 'TALONA TALBOT',
  },
  { id: '114022', value: 'DAVID BERRYMAN', agent_Id: 'dberryma', supervisor_Id: 'talona', supervisor: 'TALONA TALBOT' },
  {
    id: '185051',
    value: 'ELIZABETH SHELTON',
    agent_Id: 'eashelto',
    supervisor_Id: 'talona',
    supervisor: 'TALONA TALBOT',
  },
  { id: '201287', value: 'MELODY ANDERSON', agent_Id: 'melander', supervisor_Id: 'talona', supervisor: 'TALONA TALBOT' },
  { id: '194762', value: 'SARAH M. HOOPER', agent_Id: 'shooper', supervisor_Id: 'talona', supervisor: 'TALONA TALBOT' },
  { id: '201394', value: 'TINA PECK', agent_Id: 'tpeck', supervisor_Id: 'talona', supervisor: 'TALONA TALBOT' },
  { id: '105454', value: 'BOYD GLEDHILL', agent_Id: 'bfgledhi', supervisor_Id: 'wallinso', supervisor: 'WADE ALLINSON' },
  { id: '151860', value: 'ELDON HAMELIN', agent_Id: 'ehamelin', supervisor_Id: 'wallinso', supervisor: 'WADE ALLINSON' },
  { id: '153592', value: 'VIDA BETTS', agent_Id: 'vbetts', supervisor_Id: 'wallinso', supervisor: 'WADE ALLINSON' },
  {
    id: '171925',
    value: 'BRADEN HOLGREEN',
    agent_Id: 'bholgree',
    supervisor_Id: 'mfeicker',
    supervisor: 'MIKE FEICKERT',
  },
  {
    id: '820013',
    value: 'MICHAEL LAWRENCE',
    agent_Id: 'mlawrenc',
    supervisor_Id: 'mfeicker',
    supervisor: 'MIKE FEICKERT',
  },
  { id: '164448', value: 'RUE LARSEN', agent_Id: 'rlarsen', supervisor_Id: 'mfeicker', supervisor: 'MIKE FEICKERT' },
  {
    id: '186576',
    value: 'TERRI L LAUCHNER',
    agent_Id: 'tlauchne',
    supervisor_Id: 'mfeicker',
    supervisor: 'MIKE FEICKERT',
  },
  {
    id: '214796',
    value: 'BRADLEY CORNELL',
    agent_Id: 'bcornell',
    supervisor_Id: 'malexand',
    supervisor: 'MIKE ALEXANDER',
  },
  {
    id: '213518',
    value: 'TRICIA ANDREASON',
    agent_Id: 'tandreas',
    supervisor_Id: 'malexand',
    supervisor: 'MIKE ALEXANDER',
  },
  { id: '171478', value: 'BRANDI HERRERA', agent_Id: 'bherrer2', supervisor_Id: 'kwood', supervisor: 'KRISTALEE WOOD' },
  { id: '120973', value: 'LEATRICE FOSTER', agent_Id: 'lfoster', supervisor_Id: 'kwood', supervisor: 'KRISTALEE WOOD' },
  { id: '197021', value: 'TERI ADAMS', agent_Id: 'taadams', supervisor_Id: 'kwood', supervisor: 'KRISTALEE WOOD' },
  { id: '210303', value: 'BRANDON ADAIR', agent_Id: 'badair', supervisor_Id: 'kcarver', supervisor: 'KATIE CARVER' },
  { id: '160737', value: 'BRIAN K. LYTHGOE', agent_Id: 'blythgoe', supervisor_Id: 'kcarver', supervisor: 'KATIE CARVER' },
  { id: '198625', value: 'CJ EVANS', agent_Id: 'cjevans', supervisor_Id: 'kcarver', supervisor: 'KATIE CARVER' },
  { id: '209418', value: 'JAKE DOWNS', agent_Id: 'jdowns', supervisor_Id: 'kcarver', supervisor: 'KATIE CARVER' },
  { id: '203821', value: 'JARED ROSE', agent_Id: 'jdrose', supervisor_Id: 'kcarver', supervisor: 'KATIE CARVER' },
  { id: '207870', value: 'LINDSEY CALL', agent_Id: 'lcall', supervisor_Id: 'kcarver', supervisor: 'KATIE CARVER' },
  { id: '165172', value: 'MIKE ARNOLD', agent_Id: 'marnold', supervisor_Id: 'kcarver', supervisor: 'KATIE CARVER' },
  { id: '166503', value: 'SETH PETERSON', agent_Id: 'speters3', supervisor_Id: 'kcarver', supervisor: 'KATIE CARVER' },
  {
    id: '189784',
    value: 'BRANDON K VOYLES',
    agent_Id: 'bvoyles',
    supervisor_Id: 'croberts',
    supervisor: 'CHRISTOPHER ROBERTS',
  },
  {
    id: '189827',
    value: 'MATTHEW G FAIRBROTHER',
    agent_Id: 'mfairbro',
    supervisor_Id: 'croberts',
    supervisor: 'CHRISTOPHER ROBERTS',
  },
  {
    id: '137754',
    value: 'BRANDON MORRILL',
    agent_Id: 'bmorrill',
    supervisor_Id: 'debrarob',
    supervisor: 'DEBRA ROBERTS',
  },
  { id: '217918', value: 'SAMANTHA PERDUE', agent_Id: 'sperdue', supervisor_Id: 'debrarob', supervisor: 'DEBRA ROBERTS' },
  { id: '196985', value: 'BRANT HODSON', agent_Id: 'bhodson', supervisor_Id: 'wluke', supervisor: 'WILLIAM LUKE' },
  { id: '210924', value: 'BRAYDEN LITTLE', agent_Id: 'blittle', supervisor_Id: 'rtgraham', supervisor: 'TODD GRAHAM' },
  { id: '198637', value: 'CARLTON NIELSEN', agent_Id: 'carltonn', supervisor_Id: 'rtgraham', supervisor: 'TODD GRAHAM' },
  { id: '214587', value: 'CODY THORNTON', agent_Id: 'codythor', supervisor_Id: 'rtgraham', supervisor: 'TODD GRAHAM' },
  { id: '203017', value: 'DAVID BEAL', agent_Id: 'ddbeal', supervisor_Id: 'rtgraham', supervisor: 'TODD GRAHAM' },
  { id: '138697', value: 'JOHN CARPENTER', agent_Id: 'jcarpen3', supervisor_Id: 'rtgraham', supervisor: 'TODD GRAHAM' },
  { id: '218143', value: 'SIERRA SPROUSE', agent_Id: 'ssprouse', supervisor_Id: 'rtgraham', supervisor: 'TODD GRAHAM' },
  { id: '175211', value: 'BRETT LARSEN', agent_Id: 'blarsen4', supervisor_Id: 'jcabbott', supervisor: 'JOSEPH C ABBOTT' },
  { id: '199160', value: 'CHASE ARAVE', agent_Id: 'chaseara', supervisor_Id: 'jcabbott', supervisor: 'JOSEPH C ABBOTT' },
  {
    id: '160284',
    value: 'DANIEL A. NIEBUHR',
    agent_Id: 'dniebuhr',
    supervisor_Id: 'jcabbott',
    supervisor: 'JOSEPH C ABBOTT',
  },
  { id: '200043', value: 'ERIK KRUGER', agent_Id: 'ekruger', supervisor_Id: 'jcabbott', supervisor: 'JOSEPH C ABBOTT' },
  { id: '206195', value: 'JACOB ALLEN', agent_Id: 'jallen2', supervisor_Id: 'jcabbott', supervisor: 'JOSEPH C ABBOTT' },
  { id: '224155', value: 'PAUL CHAVEZ', agent_Id: 'pchavez', supervisor_Id: 'jcabbott', supervisor: 'JOSEPH C ABBOTT' },
  {
    id: '184537',
    value: 'REMICK UNDERWOOD',
    agent_Id: 'runderwo',
    supervisor_Id: 'jcabbott',
    supervisor: 'JOSEPH C ABBOTT',
  },
  {
    id: '211830',
    value: 'RICHARD REYNERTSON',
    agent_Id: 'rreynert',
    supervisor_Id: 'jcabbott',
    supervisor: 'JOSEPH C ABBOTT',
  },
  { id: '135666', value: 'SPENCER PUGH', agent_Id: 'spugh', supervisor_Id: 'jcabbott', supervisor: 'JOSEPH C ABBOTT' },
  { id: '189824', value: 'BRIAN M ANHDER', agent_Id: 'banhder', supervisor_Id: 'tbanks', supervisor: 'TERRY BANKS' },
  { id: '202326', value: 'CADEN WALKER', agent_Id: 'cwalker1', supervisor_Id: 'tbanks', supervisor: 'TERRY BANKS' },
  { id: '107846', value: 'DAMON PARCELL', agent_Id: 'dparcell', supervisor_Id: 'tbanks', supervisor: 'TERRY BANKS' },
  { id: '196377', value: 'RICHARD WAGER', agent_Id: 'richardw', supervisor_Id: 'tbanks', supervisor: 'TERRY BANKS' },
  { id: '134421', value: 'SARAH TORGENSON', agent_Id: 'storgens', supervisor_Id: 'tbanks', supervisor: 'TERRY BANKS' },
  { id: '101603', value: 'SHON G LUNT', agent_Id: 'shonlunt', supervisor_Id: 'tbanks', supervisor: 'TERRY BANKS' },
  {
    id: '158592',
    value: 'BRIAN PETERSON',
    agent_Id: 'bpeters2',
    supervisor_Id: 'rcervant',
    supervisor: 'RUBEN CERVANTES',
  },
  {
    id: '195173',
    value: 'DERRICK CUMBEE',
    agent_Id: 'dcumbee',
    supervisor_Id: 'rcervant',
    supervisor: 'RUBEN CERVANTES',
  },
  { id: '193651', value: 'JAMES FOSTER', agent_Id: 'jamesfos', supervisor_Id: 'rcervant', supervisor: 'RUBEN CERVANTES' },
  {
    id: '183009',
    value: 'RICARDO PEDROZA',
    agent_Id: 'rpedroza',
    supervisor_Id: 'rcervant',
    supervisor: 'RUBEN CERVANTES',
  },
  {
    id: '214813',
    value: 'STEVEN GARRETT',
    agent_Id: 'sgarret1',
    supervisor_Id: 'rcervant',
    supervisor: 'RUBEN CERVANTES',
  },
  { id: '177962', value: 'TYLER BUTLER', agent_Id: 'tylerbut', supervisor_Id: 'rcervant', supervisor: 'RUBEN CERVANTES' },
  { id: '155404', value: 'BRIAN TERVORT', agent_Id: 'btervort', supervisor_Id: 'bbeesley', supervisor: 'BLAKE BEESLEY' },
  { id: '182036', value: 'DANE ISBELL', agent_Id: 'disbell', supervisor_Id: 'bbeesley', supervisor: 'BLAKE BEESLEY' },
  { id: '207148', value: 'DEAN ADAMS', agent_Id: 'dadams2', supervisor_Id: 'bbeesley', supervisor: 'BLAKE BEESLEY' },
  { id: '187208', value: 'JORDAN HORST', agent_Id: 'jhorst', supervisor_Id: 'bbeesley', supervisor: 'BLAKE BEESLEY' },
  { id: '164327', value: 'TANYA JAMIESON', agent_Id: 'tjamieso', supervisor_Id: 'bbeesley', supervisor: 'BLAKE BEESLEY' },
  { id: '113557', value: 'TIMOTHY ROYBAL', agent_Id: 'troybal', supervisor_Id: 'bbeesley', supervisor: 'BLAKE BEESLEY' },
  { id: '184233', value: 'BRYAN S BRITTON', agent_Id: 'bbritton', supervisor_Id: 'dtrahan', supervisor: 'DAVID TRAHAN' },
  { id: '196365', value: 'DAN HEATH', agent_Id: 'danheath', supervisor_Id: 'dtrahan', supervisor: 'DAVID TRAHAN' },
  { id: '198447', value: 'MARC MILLER', agent_Id: 'marcmill', supervisor_Id: 'dtrahan', supervisor: 'DAVID TRAHAN' },
  { id: '196984', value: 'MARIANNE KIM', agent_Id: 'mkim', supervisor_Id: 'dtrahan', supervisor: 'DAVID TRAHAN' },
  { id: '193656', value: 'STEVEN BRIMHALL', agent_Id: 'sbrimhal', supervisor_Id: 'dtrahan', supervisor: 'DAVID TRAHAN' },
  { id: '161763', value: 'TLEENA CAMPBELL', agent_Id: 'tleenaca', supervisor_Id: 'dtrahan', supervisor: 'DAVID TRAHAN' },
  { id: '181742', value: 'WAYNE ROSE', agent_Id: 'wrose', supervisor_Id: 'dtrahan', supervisor: 'DAVID TRAHAN' },
  { id: '218206', value: 'CADIN BEARNSON', agent_Id: 'cbearnso', supervisor_Id: 'bfgledhi', supervisor: 'BOYD GLEDHILL' },
  {
    id: '213399',
    value: 'CAJUN ERCANBRACK',
    agent_Id: 'cercanbr',
    supervisor_Id: 'bfgledhi',
    supervisor: 'BOYD GLEDHILL',
  },
  {
    id: '218549',
    value: 'DUSTIN P PETERSON',
    agent_Id: 'dppeters',
    supervisor_Id: 'bfgledhi',
    supervisor: 'BOYD GLEDHILL',
  },
  {
    id: '205096',
    value: 'ILIANA SEBREROS VALDEZ',
    agent_Id: 'ilianase',
    supervisor_Id: 'bfgledhi',
    supervisor: 'BOYD GLEDHILL',
  },
  { id: '169896', value: 'KRYSTAL HELMS', agent_Id: 'kwidner', supervisor_Id: 'bfgledhi', supervisor: 'BOYD GLEDHILL' },
  { id: '222823', value: 'LACIE HISLOP', agent_Id: 'lhislop', supervisor_Id: 'bfgledhi', supervisor: 'BOYD GLEDHILL' },
  {
    id: '215545',
    value: 'NICHOLAS BARNES',
    agent_Id: 'nbarnes2',
    supervisor_Id: 'bfgledhi',
    supervisor: 'BOYD GLEDHILL',
  },
  { id: '209919', value: 'TYLER CONLEY', agent_Id: 'tconley', supervisor_Id: 'bfgledhi', supervisor: 'BOYD GLEDHILL' },
  { id: '2036498', value: 'CAM JARVIS', agent_Id: 'camjarvi', supervisor_Id: 'cmhansen', supervisor: 'CLINTON M HANSEN' },
  {
    id: '218834',
    value: 'TREASA STEWART',
    agent_Id: 'tsstewar',
    supervisor_Id: 'cmhansen',
    supervisor: 'CLINTON M HANSEN',
  },
  {
    id: '203008',
    value: 'CARSON CLEMMENS',
    agent_Id: 'cclemmen',
    supervisor_Id: 'jherman3',
    supervisor: 'JOSEPH HERMAN',
  },
  {
    id: '139848',
    value: 'CHRISTOPHER MICKELSON',
    agent_Id: 'cmickels',
    supervisor_Id: 'jherman3',
    supervisor: 'JOSEPH HERMAN',
  },
  { id: '203054', value: 'DREW JOHNSON', agent_Id: 'drewjohn', supervisor_Id: 'jherman3', supervisor: 'JOSEPH HERMAN' },
  { id: '216569', value: 'ERICK ORTEGA', agent_Id: 'eortega', supervisor_Id: 'jherman3', supervisor: 'JOSEPH HERMAN' },
  { id: '197501', value: 'JACLYN PACE', agent_Id: 'jpace2', supervisor_Id: 'jherman3', supervisor: 'JOSEPH HERMAN' },
  { id: '204835', value: 'RUSSELL ADAMS', agent_Id: 'russella', supervisor_Id: 'jherman3', supervisor: 'JOSEPH HERMAN' },
  { id: '203041', value: 'CASEY BARNEY', agent_Id: 'cbarney', supervisor_Id: 'ahendrix', supervisor: 'ANGELA HENDRIX' },
  {
    id: '185693',
    value: 'CHRISTINE E GONZALEZ',
    agent_Id: 'cegonzal',
    supervisor_Id: 'ahendrix',
    supervisor: 'ANGELA HENDRIX',
  },
  { id: '184262', value: 'JOHN B WHITED', agent_Id: 'jwhited', supervisor_Id: 'ahendrix', supervisor: 'ANGELA HENDRIX' },
  {
    id: '169545',
    value: 'MICHAEL WESTWOOD',
    agent_Id: 'mwestwoo',
    supervisor_Id: 'ahendrix',
    supervisor: 'ANGELA HENDRIX',
  },
  {
    id: '164654',
    value: 'CATHERINE GUNDERSON',
    agent_Id: 'cgunders',
    supervisor_Id: 'dfrankli',
    supervisor: 'DENNIS FRANKLIN',
  },
  { id: '158584', value: 'JAMES CLEGG', agent_Id: 'jclegg', supervisor_Id: 'dfrankli', supervisor: 'DENNIS FRANKLIN' },
  { id: '172876', value: 'KIRK LAMBERT', agent_Id: 'klambert', supervisor_Id: 'dfrankli', supervisor: 'DENNIS FRANKLIN' },
  { id: '208962', value: 'CATIE ONEAL', agent_Id: 'cribera', supervisor_Id: 'jblau', supervisor: 'JENNIFER BLAU' },
  { id: '187323', value: 'ELIZABETH BROWN', agent_Id: 'edbrown', supervisor_Id: 'jblau', supervisor: 'JENNIFER BLAU' },
  { id: '186570', value: 'HEATHER MCCOY', agent_Id: 'hmccoy', supervisor_Id: 'jblau', supervisor: 'JENNIFER BLAU' },
  { id: '211988', value: 'JEFF JONES', agent_Id: 'jjones2', supervisor_Id: 'jblau', supervisor: 'JENNIFER BLAU' },
  { id: '193561', value: 'LYNNETTE HUNTING', agent_Id: 'lhunting', supervisor_Id: 'jblau', supervisor: 'JENNIFER BLAU' },
  { id: '211965', value: 'TAUSHA BREEZE', agent_Id: 'tbreeze', supervisor_Id: 'jblau', supervisor: 'JENNIFER BLAU' },
  { id: '221802', value: 'CHASE TISCHER', agent_Id: 'ctischer', supervisor_Id: 'clund', supervisor: 'CLINTON LUND' },
  { id: '181715', value: 'JAEME SOLIS', agent_Id: 'jsolis', supervisor_Id: 'clund', supervisor: 'CLINTON LUND' },
  { id: '203780', value: 'JARED NAYLOR', agent_Id: 'jarednay', supervisor_Id: 'clund', supervisor: 'CLINTON LUND' },
  { id: '212423', value: 'JASON CALL', agent_Id: 'jasoncal', supervisor_Id: 'clund', supervisor: 'CLINTON LUND' },
  { id: '213726', value: 'TIMOTHY OTTESEN', agent_Id: 'tottesen', supervisor_Id: 'clund', supervisor: 'CLINTON LUND' },
  { id: '152612', value: 'CHRIS COOMBS', agent_Id: 'ccoombs', supervisor_Id: 'dreed', supervisor: 'DUANE REED' },
  { id: '205356', value: 'DILON CHRISTENSEN', agent_Id: 'dilon', supervisor_Id: 'dreed', supervisor: 'DUANE REED' },
  { id: '158606', value: 'JAY L COATES', agent_Id: 'jcoates', supervisor_Id: 'dreed', supervisor: 'DUANE REED' },
  { id: '213497', value: 'MATTHEW COTTRELL', agent_Id: 'mcottrel', supervisor_Id: 'dreed', supervisor: 'DUANE REED' },
  { id: '216645', value: 'TAYLOR CARTER', agent_Id: 'tcarter4', supervisor_Id: 'dreed', supervisor: 'DUANE REED' },
  { id: '211818', value: 'TYLER GREEN', agent_Id: 'tgreen1', supervisor_Id: 'dreed', supervisor: 'DUANE REED' },
  { id: '204740', value: 'CHRIS OBORN', agent_Id: 'coborn', supervisor_Id: 'rnorton', supervisor: 'RANDI L. NORTON' },
  { id: '210292', value: 'CORY ADERS', agent_Id: 'caders', supervisor_Id: 'rnorton', supervisor: 'RANDI L. NORTON' },
  { id: '199219', value: 'DESIREE GREEN', agent_Id: 'dkgreen', supervisor_Id: 'rnorton', supervisor: 'RANDI L. NORTON' },
  {
    id: '162323',
    value: 'GEORGE BLACKBURN',
    agent_Id: 'gblackbu',
    supervisor_Id: 'rnorton',
    supervisor: 'RANDI L. NORTON',
  },
  { id: '203200', value: 'GEORGE LAUB', agent_Id: 'gslaub', supervisor_Id: 'rnorton', supervisor: 'RANDI L. NORTON' },
  {
    id: '180489',
    value: 'JENNIFER ROBERTSON',
    agent_Id: 'jjrobert',
    supervisor_Id: 'rnorton',
    supervisor: 'RANDI L. NORTON',
  },
  {
    id: '202567',
    value: 'MARIELA RENTER',
    agent_Id: 'marenter',
    supervisor_Id: 'rnorton',
    supervisor: 'RANDI L. NORTON',
  },
  { id: '197832', value: 'PAUL EPPERSON', agent_Id: 'pepperso', supervisor_Id: 'rnorton', supervisor: 'RANDI L. NORTON' },
  { id: '207219', value: 'STACY INGLEBY', agent_Id: 'singleby', supervisor_Id: 'rnorton', supervisor: 'RANDI L. NORTON' },
  { id: '164752', value: 'CHRIS PACKER', agent_Id: 'cpacker', supervisor_Id: 'baitken', supervisor: 'BRYAN S. AITKEN' },
  { id: '192931', value: 'DAVID CUMMINS', agent_Id: 'dcummins', supervisor_Id: 'baitken', supervisor: 'BRYAN S. AITKEN' },
  { id: '185646', value: 'CHRISTA COLBY', agent_Id: 'cscolby', supervisor_Id: 'khouston', supervisor: 'KAYE HOUSTON' },
  {
    id: '164732',
    value: 'CHRISTINA CURTIS',
    agent_Id: 'ccurtis2',
    supervisor_Id: 'khouston',
    supervisor: 'KAYE HOUSTON',
  },
  { id: '217138', value: 'TRICIA TRACY', agent_Id: 'ttracy2', supervisor_Id: 'khouston', supervisor: 'KAYE HOUSTON' },
  { id: '171980', value: 'CHRISTOPHER MOORE', agent_Id: 'cmoore4', supervisor_Id: 'kkeller3', supervisor: 'KEN KELLER' },
  { id: '115171', value: 'CORRIN GIBBONS', agent_Id: 'cgibbons', supervisor_Id: 'kkeller3', supervisor: 'KEN KELLER' },
  { id: '210998', value: 'KATEY ACORD', agent_Id: 'kfacord', supervisor_Id: 'kkeller3', supervisor: 'KEN KELLER' },
  { id: '102075', value: 'RICHARD BILLINGS', agent_Id: 'rbilling', supervisor_Id: 'kkeller3', supervisor: 'KEN KELLER' },
  { id: '188451', value: 'CLAUDIO B CUEVA', agent_Id: 'ccueva', supervisor_Id: 'abrown', supervisor: 'ANTHONY BROWN' },
  { id: '116535', value: 'GREG SMITH', agent_Id: 'gsmith2', supervisor_Id: 'abrown', supervisor: 'ANTHONY BROWN' },
  {
    id: '192702',
    value: 'CLIFFORD D CABANILLA',
    agent_Id: 'ccabanil',
    supervisor_Id: 'rcarter2',
    supervisor: 'RANDI CARTER',
  },
  { id: '176283', value: 'GERIT ASAY', agent_Id: 'gasay', supervisor_Id: 'rcarter2', supervisor: 'RANDI CARTER' },
  { id: '214176', value: 'CLIFFORD HENDRY', agent_Id: 'chendry', supervisor_Id: 'bhamblin', supervisor: 'BRIAN HAMBLIN' },
  { id: '207611', value: 'JUVAL TORRES', agent_Id: 'juvalflo', supervisor_Id: 'bhamblin', supervisor: 'BRIAN HAMBLIN' },
  { id: '103975', value: 'KERRIE TURRILL', agent_Id: 'kturrill', supervisor_Id: 'bhamblin', supervisor: 'BRIAN HAMBLIN' },
  {
    id: '192643',
    value: 'MICHAEL D HIGGINS',
    agent_Id: 'michaelh',
    supervisor_Id: 'bhamblin',
    supervisor: 'BRIAN HAMBLIN',
  },
  {
    id: '223586',
    value: 'NICHOLAS CONTRYS',
    agent_Id: 'ncontrys',
    supervisor_Id: 'bhamblin',
    supervisor: 'BRIAN HAMBLIN',
  },
  { id: '207106', value: 'CODY JOSEPHSON', agent_Id: 'cjosephs', supervisor_Id: 'jderbidg', supervisor: 'JOHN DERBIDGE' },
  { id: '192421', value: 'MIGUEL SOSA', agent_Id: 'miguelso', supervisor_Id: 'jderbidg', supervisor: 'JOHN DERBIDGE' },
  {
    id: '193618',
    value: 'COLE KATSILAS',
    agent_Id: 'ckatsila',
    supervisor_Id: 'neldridg',
    supervisor: 'NATHAN ELDRIDGE',
  },
  {
    id: '169052',
    value: 'DANIEL GUNRUD',
    agent_Id: 'dgunrud',
    supervisor_Id: 'jloertsc',
    supervisor: 'JASON LOERTSCHER',
  },
  { id: '202355', value: 'JASON NUNEZ', agent_Id: 'jnunez', supervisor_Id: 'jloertsc', supervisor: 'JASON LOERTSCHER' },
  { id: '109983', value: 'JEREMY SHAW', agent_Id: 'jshaw', supervisor_Id: 'jloertsc', supervisor: 'JASON LOERTSCHER' },
  {
    id: '205224',
    value: 'JORDAN LAVENTURE',
    agent_Id: 'jlaventu',
    supervisor_Id: 'jloertsc',
    supervisor: 'JASON LOERTSCHER',
  },
  {
    id: '131088',
    value: 'MARK THOMSEN',
    agent_Id: 'mthomsen',
    supervisor_Id: 'jloertsc',
    supervisor: 'JASON LOERTSCHER',
  },
  {
    id: '191523',
    value: 'TIMOTHY JESSOP',
    agent_Id: 'tjessop',
    supervisor_Id: 'jloertsc',
    supervisor: 'JASON LOERTSCHER',
  },
  { id: '167131', value: 'TOLBY POT', agent_Id: 'tpot', supervisor_Id: 'jloertsc', supervisor: 'JASON LOERTSCHER' },
  { id: '141333', value: 'DANIEL M. BOYDEN', agent_Id: 'dboyden', supervisor_Id: 'oparry', supervisor: 'OOGI PARRY' },
  {
    id: '213367',
    value: 'DANIELLE CARPENTER',
    agent_Id: 'dancarpe',
    supervisor_Id: 'bherrer2',
    supervisor: 'BRANDI HERRERA',
  },
  { id: '212024', value: 'JASON RAMSEY', agent_Id: 'jramsey', supervisor_Id: 'bherrer2', supervisor: 'BRANDI HERRERA' },
  { id: '171972', value: 'STACY NELSON', agent_Id: 'snnelson', supervisor_Id: 'bherrer2', supervisor: 'BRANDI HERRERA' },
  { id: '187203', value: 'DAVID PENROD', agent_Id: 'dppenrod', supervisor_Id: 'rproctor', supervisor: 'RYAN PROCTOR' },
  {
    id: '201636',
    value: 'SHANNON MCKIEARNAN',
    agent_Id: 'smckiear',
    supervisor_Id: 'rproctor',
    supervisor: 'RYAN PROCTOR',
  },
  { id: '164564', value: 'DEBBIE GATES', agent_Id: 'dgates', supervisor_Id: 'srobins2', supervisor: 'SETH ROBINSON' },
  { id: '204011', value: 'GREG HUNT', agent_Id: 'ghunt', supervisor_Id: 'srobins2', supervisor: 'SETH ROBINSON' },
  {
    id: '184235',
    value: 'JEFFERY T HOWCROFT',
    agent_Id: 'jthowcro',
    supervisor_Id: 'srobins2',
    supervisor: 'SETH ROBINSON',
  },
  {
    id: '201196',
    value: 'LUKE CHRISTENSEN',
    agent_Id: 'lukechri',
    supervisor_Id: 'srobins2',
    supervisor: 'SETH ROBINSON',
  },
  { id: '218184', value: 'SARAH WILSON', agent_Id: 'sarahwil', supervisor_Id: 'srobins2', supervisor: 'SETH ROBINSON' },
  { id: '221543', value: 'STEVEN AUBREY', agent_Id: 'saubrey', supervisor_Id: 'srobins2', supervisor: 'SETH ROBINSON' },
  {
    id: '104483',
    value: 'DEBBIE PARENZIN',
    agent_Id: 'dparenzi',
    supervisor_Id: 'bmiller2',
    supervisor: 'BRANWEN MILLER',
  },
  {
    id: '155807',
    value: 'JOSLYN PILLING',
    agent_Id: 'jpilling',
    supervisor_Id: 'bmiller2',
    supervisor: 'BRANWEN MILLER',
  },
  { id: '211984', value: 'ELIZABETH IAVASILE', agent_Id: 'eiavasil', supervisor_Id: 'jclegg', supervisor: 'JAMES CLEGG' },
  { id: '152637', value: 'GLENN C. SMITH', agent_Id: 'gsmith4', supervisor_Id: 'jclegg', supervisor: 'JAMES CLEGG' },
  { id: '120108', value: 'JAMES DUCKWORTH', agent_Id: 'jduckwor', supervisor_Id: 'jclegg', supervisor: 'JAMES CLEGG' },
  { id: '130103', value: 'JARED M. MINNOCH', agent_Id: 'jminnoch', supervisor_Id: 'jclegg', supervisor: 'JAMES CLEGG' },
  { id: '190147', value: 'JOSH BAIRD', agent_Id: 'joshbair', supervisor_Id: 'jclegg', supervisor: 'JAMES CLEGG' },
  { id: '202334', value: 'SCOTT NORTON', agent_Id: 'scnorton', supervisor_Id: 'jclegg', supervisor: 'JAMES CLEGG' },
  { id: '224056', value: 'IRENE THORNTON', agent_Id: 'ithornto', supervisor_Id: 'khizer', supervisor: 'KEVIN HIZER' },
  { id: '191515', value: 'JOE A MURPHY', agent_Id: 'joemurph', supervisor_Id: 'khizer', supervisor: 'KEVIN HIZER' },
  { id: '176053', value: 'JOHN KELLEY', agent_Id: 'jkelley', supervisor_Id: 'khizer', supervisor: 'KEVIN HIZER' },
  { id: '218040', value: 'JOSHUA MORRIS', agent_Id: 'jamorris', supervisor_Id: 'khizer', supervisor: 'KEVIN HIZER' },
  { id: '111596', value: 'KAREN PREVEDEL', agent_Id: 'kprevede', supervisor_Id: 'khizer', supervisor: 'KEVIN HIZER' },
  { id: '208492', value: 'KYLE COOPER', agent_Id: 'kjcooper', supervisor_Id: 'khizer', supervisor: 'KEVIN HIZER' },
  { id: '192939', value: 'NIC DEHAAS', agent_Id: 'ndehaas', supervisor_Id: 'khizer', supervisor: 'KEVIN HIZER' },
  { id: '178144', value: 'RICK MORGAN', agent_Id: 'rickmorg', supervisor_Id: 'khizer', supervisor: 'KEVIN HIZER' },
  { id: '211910', value: 'JACOB COLEMAN', agent_Id: 'jcoleman', supervisor_Id: 'wmorell', supervisor: 'WILLIAM MORELL' },
  { id: '204130', value: 'JAMES MORRIS', agent_Id: 'jlmorris', supervisor_Id: 'wmorell', supervisor: 'WILLIAM MORELL' },
  { id: '158571', value: 'JASON BEHUNIN', agent_Id: 'jbehunin', supervisor_Id: 'wmorell', supervisor: 'WILLIAM MORELL' },
  { id: '166500', value: 'KYLE GROVES', agent_Id: 'kgroves', supervisor_Id: 'wmorell', supervisor: 'WILLIAM MORELL' },
  { id: '203015', value: 'LLOYD DURDEN', agent_Id: 'ldurden', supervisor_Id: 'wmorell', supervisor: 'WILLIAM MORELL' },
  {
    id: '188397',
    value: 'MATTHEW D LAMBERT',
    agent_Id: 'matthewl',
    supervisor_Id: 'wmorell',
    supervisor: 'WILLIAM MORELL',
  },
  { id: '183494', value: 'NELS COOK', agent_Id: 'ncook', supervisor_Id: 'wmorell', supervisor: 'WILLIAM MORELL' },
  { id: '212110', value: 'JADE WATKIN', agent_Id: 'jwatkin', supervisor_Id: 'dsampson', supervisor: 'DENISE SAMPSON' },
  {
    id: '209562',
    value: 'KATHRYN REDING',
    agent_Id: 'kathrynr',
    supervisor_Id: 'dsampson',
    supervisor: 'DENISE SAMPSON',
  },
  { id: '180119', value: 'KATHY COWLEY', agent_Id: 'kcowley', supervisor_Id: 'dsampson', supervisor: 'DENISE SAMPSON' },
  { id: '212034', value: 'RENA CRAIG', agent_Id: 'rlcraig', supervisor_Id: 'dsampson', supervisor: 'DENISE SAMPSON' },
  { id: '141679', value: 'JAMES CAMPOS', agent_Id: 'jcampos', supervisor_Id: 'amccain', supervisor: 'ANDREW MCCAIN' },
  { id: '183823', value: 'KEVIN HIZER', agent_Id: 'khizer', supervisor_Id: 'amccain', supervisor: 'ANDREW MCCAIN' },
  { id: '114821', value: 'MICHAEL ADAM', agent_Id: 'madam', supervisor_Id: 'amccain', supervisor: 'ANDREW MCCAIN' },
  { id: '200601', value: 'JASON BOWLER', agent_Id: 'jbowler', supervisor_Id: 'dschugk2', supervisor: 'DANIEL SCHUGK' },
  { id: '197503', value: 'KAELA BAIRD', agent_Id: 'kaelabai', supervisor_Id: 'dschugk2', supervisor: 'DANIEL SCHUGK' },
  {
    id: '164440',
    value: 'MICHAEL MARTELL',
    agent_Id: 'mmartell',
    supervisor_Id: 'dschugk2',
    supervisor: 'DANIEL SCHUGK',
  },
  { id: '163399', value: 'NICK WARD', agent_Id: 'nward', supervisor_Id: 'dschugk2', supervisor: 'DANIEL SCHUGK' },
  {
    id: '173027',
    value: 'JASON FAIRBANKS',
    agent_Id: 'jfairban',
    supervisor_Id: 'cgreenbe',
    supervisor: 'CRAIG GREENBERG',
  },
  { id: '160997', value: 'JASON HANSEN', agent_Id: 'jhansen4', supervisor_Id: 'tshock', supervisor: 'TRACY SHOCK' },
  { id: '152034', value: 'SHAWN BEKKEMELLOM', agent_Id: 'shawnbek', supervisor_Id: 'tshock', supervisor: 'TRACY SHOCK' },
  {
    id: '136672',
    value: 'JASON R NIELSON',
    agent_Id: 'jnielso2',
    supervisor_Id: 'jhutchin',
    supervisor: 'JASON HUTCHINSON',
  },
  { id: '113542', value: 'STACY CLARK', agent_Id: 'sclark', supervisor_Id: 'jhutchin', supervisor: 'JASON HUTCHINSON' },
  {
    id: '159946',
    value: 'JEFF SHARDLOW',
    agent_Id: 'jshardlo',
    supervisor_Id: 'agriffit',
    supervisor: 'AIMEE GRIFFITHS',
  },
  { id: '161063', value: 'JEREMY BROWN', agent_Id: 'jbrown5', supervisor_Id: 'cbuchana', supervisor: 'CRAIG BUCHANAN' },
  {
    id: '199002',
    value: 'JEREMY DAVENPORT',
    agent_Id: 'jdavenpo',
    supervisor_Id: 'craighan',
    supervisor: 'CRAIG HANSEN',
  },
  { id: '203781', value: 'PRESTON HANSEN', agent_Id: 'phansen1', supervisor_Id: 'craighan', supervisor: 'CRAIG HANSEN' },
  { id: '163538', value: 'JESSICA COOK', agent_Id: 'jcook3', supervisor_Id: 'jweindor', supervisor: 'JENNIFER CALVO' },
  { id: '169829', value: 'JOHN DERBIDGE', agent_Id: 'jderbidg', supervisor_Id: 'rcid', supervisor: 'ROBERT CID' },
  {
    id: '191686',
    value: 'KATHY M PARASKEVA',
    agent_Id: 'kparaske',
    supervisor_Id: 'dparenzi',
    supervisor: 'DEBBIE PARENZIN',
  },
  { id: '189898', value: 'PEGGY PLATT', agent_Id: 'pplatt', supervisor_Id: 'dparenzi', supervisor: 'DEBBIE PARENZIN' },
  { id: '219287', value: 'KIERSTEN SHELLEY', agent_Id: 'kshelley', supervisor_Id: 'samjack', supervisor: 'SAM JACKMAN' },
  { id: '165308', value: 'SAMANTHA KEELE', agent_Id: 'skeele', supervisor_Id: 'samjack', supervisor: 'SAM JACKMAN' },
  { id: '193266', value: 'KIRK HAZLETON', agent_Id: 'khazleto', supervisor_Id: 'akiesel', supervisor: 'ALLEN KIESEL' },
  { id: '218720', value: 'KRISTIE HILL', agent_Id: 'kristieh', supervisor_Id: 'baguilar', supervisor: 'BRANDI AGUILAR' },
  {
    id: '208301',
    value: 'MALISA DOERING',
    agent_Id: 'mdoering',
    supervisor_Id: 'dfullert',
    supervisor: 'DENISE R FULLERTON',
  },
  { id: '198998', value: 'MARIAH JACKSON', agent_Id: 'mrosadoj', supervisor_Id: 'bhodson', supervisor: 'BRANT HODSON' },
  { id: '115612', value: 'MARK COLBY', agent_Id: 'mcolby', supervisor_Id: 'ihale', supervisor: 'IRVIN B. HALE' },
  { id: '154378', value: 'WILLIAM MORELL', agent_Id: 'wmorell', supervisor_Id: 'ihale', supervisor: 'IRVIN B. HALE' },
  { id: '150674', value: 'MITCHELL CARVER', agent_Id: 'mcarver', supervisor_Id: 'syeates', supervisor: 'STEVE YEATES' },
  {
    id: '213907',
    value: 'NICHOLAS PEAY',
    agent_Id: 'nicholas',
    supervisor_Id: 'aparchul',
    supervisor: 'ANDREW ARCHULETA',
  },
  {
    id: '195092',
    value: 'ROSARIO RAMSEY',
    agent_Id: 'rramsey',
    supervisor_Id: 'jshipman',
    supervisor: 'JENNIFER BOLTON',
  },
  {
    id: '157873',
    value: 'SCOTT C. STEPHENS',
    agent_Id: 'sstephen',
    supervisor_Id: 'jdraper',
    supervisor: 'JOSHUA DRAPER',
  },
  { id: '119975', value: 'TIM GREEN', agent_Id: 'tgreen', supervisor_Id: 'jcook3', supervisor: 'JESSICA COOK' },
];

const ids = new Set([]);
const supervisorLookup = [];

agentLookup.forEach((item) => {
  if (!ids.has(item.supervisor_Id)) {
    ids.add(item.supervisor_Id);
    supervisorLookup.push({ value: item.supervisor, id: item.supervisor_Id });
  }
});

const supervisionContactDays = [30, 60, 90, 180];

const counties = [
  'BEAVER',
  'BOX ELDER',
  'CACHE',
  'CARBON',
  'DAGGETT',
  'DAVIS',
  'DUCHESNE',
  'EMERY',
  'GARFIELD',
  'GRAND',
  'IRON',
  'JUAB',
  'KANE',
  'MILLARD',
  'MORGAN',
  'PIUTE',
  'RICH',
  'SALT LAKE',
  'SAN JUAN',
  'SANPETE',
  'SEVIER',
  'SUMMIT',
  'TOOELE',
  'UINTAH',
  'UTAH',
  'WASATCH',
  'WASHINGTON',
  'WAYNE',
  'WEBER',
];

export { agentLookup, counties, mainGangs, offenseTypes, supervisionContactDays, supervisionItems, supervisorLookup };
