const supervisionItems = [{
    name: 'CCC',
    id: 'CCC',
    default: false
}, {
    name: 'PVP',
    id: 'PVP',
    default: false
}, {
    name: 'COMP',
    id: 'COMP',
    default: false
}, {
    name: 'DEP',
    id: 'DEP',
    default: false
}, {
    name: 'EM',
    id: 'EM',
    default: true
}, {
    name: 'GPS',
    id: 'GPS',
    default: true
}, {
    name: 'SO',
    id: 'SO',
    default: true
}, {
    name: 'SO-A',
    id: 'SO-A',
    default: true
}, {
    name: 'SO-B',
    id: 'SO-B',
    default: true
}, {
    name: 'SO-C',
    id: 'SO-C',
    default: true
}, {
    name: 'FUG',
    id: 'FUG',
    default: false
}, {
    name: 'INCAR',
    id: 'INCAR',
    default: false
}, {
    name: 'RESID',
    id: 'RESID',
    default: false
}, {
    name: 'DRUG CT',
    id: 'DRUG CT',
    default: false
}, {
    name: 'DORA',
    id: 'DORA',
    default: true
}, {
    name: 'ECR',
    id: 'ECR',
    default: true
}, {
    name: 'FOSI',
    id: 'FOSI',
    default: true
}, {
    name: 'IG INT',
    id: 'IG INT',
    default: true
}, {
    name: 'MIO',
    id: 'MIO',
    default: true
}];

const mainGangs = [{
    name: 'sureno',
    id: 1
}, {
    name: 'nortenos',
    id: 2
}, {
    name: 'omg - outlaw motorcycl',
    id: 3
}, {
    name: 'white supremacist',
    id: 4
}, {
    name: 'crip',
    id: 5
}, {
    name: 'bloods',
    id: 6
}, {
    name: 'people nation',
    id: 7
}, {
    name: 'folk nation',
    id: 8
}, {
    name: 'others',
    id: 9
}, {
    name: 'no type specified',
    id: 10
}, {
    name: 'vlt',
    id: 11
}, {
    name: 'o13',
    id: 12
}, {
    name: 'qvo',
    id: 13
}];

const offenseTypes = [{
    name: 'murder',
    id: 'A'
}, {
    name: 'sex/registerable',
    id: 'D'
}, {
    name: 'sex/non-registerable',
    id: 'E'
}, {
    name: 'person',
    id: 'G'
}, {
    name: 'alcohol & drug',
    id: 'J'
}, {
    name: 'property',
    id: 'M'
}, {
    name: 'weapons',
    id: 'P'
}, {
    name: 'driving',
    id: 'S'
}, {
    name: 'other',
    id: 'V'
}, {
    name: 'drug possession only',
    id: 'X'
}, {
    name: 'unknown',
    id: 'Z'
}];

const agents = [
    { value: 'AARON ANDERSON', supervisor: 'KODY FLOYD' },
    { value: 'AARON CARVER', supervisor: 'JAMES CAMPOS' },
    { value: 'AARON LEE', supervisor: 'KIRK LAMBERT' },
    { value: 'AARON POWELL', supervisor: 'VIDA BETTS' },
    { value: 'AARON SMITH', supervisor: 'ERIC PRICE' },
    { value: 'ADAM CHARD', supervisor: 'MICHAEL RENCKERT' },
    { value: 'ADAM WAHLBERG', supervisor: 'DORIAN WOLFE' },
    { value: 'AL BELL', supervisor: 'BRIAN HAMBLIN' },
    { value: 'ALAN DRESSLER', supervisor: 'TONY GARRETT' },
    { value: 'ALBERT WHITEHORSE', supervisor: 'WADE ALLINSON' },
    { value: 'ALEJANDRO REYES-GALDAMEZ', supervisor: 'FELICIA LAGARCE' },
    { value: 'ALLEN RUECKERT', supervisor: 'STEVE WILLIAMSON' },
    { value: 'AMBERDEE MILLER', supervisor: 'RANDI CARTER' },
    { value: 'ANA M MASCIANTONIO', supervisor: 'JAMES ADAMSON' },
    { value: 'ANDREA HAIGHT', supervisor: 'BLAKE BEESLEY' },
    { value: 'ANDREW ARCHULETA', supervisor: 'KILEY D WILLIS' },
    { value: 'ANDREW DALTON', supervisor: 'CLINTON LUND' },
    { value: 'ANDREW MCKEON', supervisor: 'JEFF SHARDLOW' },
    { value: 'ANGELA HENDRIX', supervisor: 'SPENCER TURLEY' },
    { value: 'ANGELA SYMONDS', supervisor: 'NATHAN ELDRIDGE' },
    { value: 'ANNETTE SALGADO', supervisor: 'SPENCER TURLEY' },
    { value: 'ANTHONY CANDELARIA', supervisor: 'KODY FLOYD' },
    { value: 'ANTOINETTE AIONO', supervisor: 'TERRY BANKS' },
    { value: 'AUDREY BROWN', supervisor: 'FELICIA LAGARCE' },
    { value: 'AUSTIN Q ROBERTS', supervisor: 'DANIEL HAYS' },
    { value: 'AUSTIN RHEES', supervisor: 'PRESTON KAY' },
    { value: 'BARRY HANSEN', supervisor: 'JAMES CLEGG' },
    { value: 'BART WOOLLEY', supervisor: 'GREG SMITH' },
    { value: 'BEAU BROMLEY', supervisor: 'JEFF SHARDLOW' },
    { value: 'BECKI WINGER', supervisor: 'PRESTON KAY' },
    { value: 'BEN BROADBENT', supervisor: 'WADE ALLINSON' },
    { value: 'BLAINE BILLS', supervisor: 'KIRK LAMBERT' },
    { value: 'BLAKE DENNEY', supervisor: 'JAMES ADAMSON' },
    { value: 'BLAKE WRIGHT', supervisor: 'TERRY BANKS' },
    { value: 'BO B REIER', supervisor: 'GREGORY PERRY' },
    { value: 'BOB HAGGERTY', supervisor: 'KATIE CARVER' },
    { value: 'BOYD GLEDHILL', supervisor: 'ELDON HAMELIN' },
    { value: 'BRAD DRAPER', supervisor: 'WADE ALLINSON' },
    { value: 'BRADLEY F JOHNSON', supervisor: 'WILLIAM LUKE' },
    { value: 'BRADY BARNEY', supervisor: 'ALLEN JULIAN' },
    { value: 'BRANDON K VOYLES', supervisor: 'DANIEL SCHUGK' },
    { value: 'BRANDON ULIBARRI', supervisor: 'DAVID LOWRY' },
    { value: 'BRANDON W MEADOWS', supervisor: 'ELDON HAMELIN' },
    { value: 'BRANIGAN M SATTERFIELD', supervisor: 'ROBERT CID' },
    { value: 'BRENDAN NISSEN', supervisor: 'KEN KELLER' },
    { value: 'BRETT CURTIS', supervisor: 'DANIEL HAYS' },
    { value: 'BRIAN K. LYTHGOE', supervisor: 'KIM BELL-HOLDEN' },
    { value: 'BRIAN M ANHDER', supervisor: 'WILLIAM LUKE' },
    { value: 'BRIAN PETERSON', supervisor: 'MICHAEL RENCKERT' },
    { value: 'BRITTAN PETERSEN', supervisor: 'BRIAN HAMBLIN' },
    { value: 'BRITTANY SHARP', supervisor: 'KILEY D WILLIS' },
    { value: 'BROCK TRESEDER', supervisor: 'JAMES CLEGG' },
    { value: 'BRYAN S BRITTON', supervisor: 'JOSHUA DRAPER' },
    { value: 'BRYAN TALBOT', supervisor: 'JAMES ADAMSON' },
    { value: 'CALVIN N. PICKETT', supervisor: 'ALLEN JULIAN' },
    { value: 'CAMILO REYES', supervisor: 'KATIE CARVER' },
    { value: 'CANDACE DOMINGO', supervisor: 'CLINTON LUND' },
    { value: 'CAROLYN MONTILLA', supervisor: 'JAMES ADAMSON' },
    { value: 'CHANNA ANDERSON', supervisor: 'VIDA BETTS' },
    { value: 'CHARLES CHAPPELL', supervisor: 'GREG SMITH' },
    { value: 'CHASE WITHERS', supervisor: 'NATHAN ELDRIDGE' },
    { value: 'CHERYL FRANDSEN', supervisor: 'VIDA BETTS' },
    { value: 'CHRIS CARTER', supervisor: 'FELICIA LAGARCE' },
    { value: 'CHRIS COOMBS', supervisor: 'KATIE CARVER' },
    { value: 'CHRIS PACKER', supervisor: 'MICHAEL ADAM' },
    { value: 'CHRISTINA CURTIS', supervisor: 'DAVID LOWRY' },
    { value: 'CHRISTINE E GONZALEZ', supervisor: 'ANGELA HENDRIX' },
    { value: 'CHRISTINE STRONG', supervisor: 'JAMES ADAMSON' },
    { value: 'CHRISTOPHER A. HOPKINS', supervisor: 'RICK SMITH' },
    { value: 'CHRISTOPHER ASTLE', supervisor: 'ANGELA HENDRIX' },
    { value: 'CHRISTOPHER BIRD', supervisor: 'GREG SMITH' },
    { value: 'CHRISTOPHER MICKELSON', supervisor: 'MICHAEL RENCKERT' },
    { value: 'CHRISTOPHER ROBERTS', supervisor: 'KODY FLOYD' },
    { value: 'CJ EVANS', supervisor: 'JAMES CLEGG' },
    { value: 'CLAUDIO B CUEVA', supervisor: 'BLAKE BEESLEY' },
    { value: 'CLAY YARDLEY', supervisor: 'JAMES CAMPOS' },
    { value: 'CLIFF HAMILTON', supervisor: 'JOSHUA DRAPER' },
    { value: 'CLINTON M HANSEN', supervisor: 'KODY FLOYD' },
    { value: 'COLE KATSILAS', supervisor: 'RICK SMITH' },
    { value: 'COLT CARSON', supervisor: 'JOSHUA DRAPER' },
    { value: 'COLTON ROTHE', supervisor: 'KODY FLOYD' },
    { value: 'CONNIE CHRISTENSEN', supervisor: 'DAVID LOWRY' },
    { value: 'COREY MCEWAN', supervisor: 'ANNETTE SALGADO' },
    { value: 'CORY R GRINT', supervisor: 'ELDON HAMELIN' },
    { value: 'CRAIG HANSEN', supervisor: 'KILEY D WILLIS' },
    { value: 'CRYSTAL BLASI', supervisor: 'KIRK LAMBERT' },
    { value: 'DANE ISBELL', supervisor: 'BLAKE BEESLEY' },
    { value: 'DANE PETERSON', supervisor: 'TERRY BANKS' },
    { value: 'DANIEL A. NIEBUHR', supervisor: 'DAVID TRAHAN' },
    { value: 'DANIEL FERRON', supervisor: 'TERRY BANKS' },
    { value: 'DANIEL GORDON', supervisor: 'ANNETTE SALGADO' },
    { value: 'DANIEL GUNRUD', supervisor: 'WILLIAM LUKE' },
    { value: 'DANIEL HAYS', supervisor: 'KARL KENNINGTON' },
    { value: 'DANIEL JORGENSEN', supervisor: 'ANNETTE SALGADO' },
    { value: 'DANTE DETTAMANTI', supervisor: 'KILEY D WILLIS' },
    { value: 'DARREN PETERSEN', supervisor: 'ROBERT CID' },
    { value: 'DARREN SWAIN', supervisor: 'ALLEN JULIAN' },
    { value: 'DAVID AH CURTIS', supervisor: 'NATHAN ELDRIDGE' },
    { value: 'DAVID ANDERSEN', supervisor: 'JEFF SHARDLOW' },
    { value: 'DAVID GAFFNEY', supervisor: 'MICHAEL RENCKERT' },
    { value: 'DAVID HANNA', supervisor: 'JEFF SHARDLOW' },
    { value: 'DAVID JENSEN', supervisor: 'KEN KELLER' },
    { value: 'DAVID JONES', supervisor: 'ANNETTE SALGADO' },
    { value: 'DAVID OWENS', supervisor: 'DAVID LOWRY' },
    { value: 'DAVID PEDERSEN', supervisor: 'JEFF SHARDLOW' },
    { value: 'DAVID TRAHAN', supervisor: 'KARL KENNINGTON' },
    { value: 'DEAN ADAMS', supervisor: 'BLAKE BEESLEY' },
    { value: 'DEBBIE PARENZIN', supervisor: 'RANDI CARTER' },
    { value: 'DEBBY JENSEN', supervisor: 'CLINTON LUND' },
    { value: 'DENTON CALL', supervisor: 'BRIAN HAMBLIN' },
    { value: 'DEON WALSER', supervisor: 'TERRY BANKS' },
    { value: 'DERRICK CUMBEE', supervisor: 'JEFF SHARDLOW' },
    { value: 'DIRK WILKINSON', supervisor: 'JOHN CARPENTER' },
    { value: 'DONNA FOX', supervisor: 'CATHERINE GUNDERSON' },
    { value: 'DOUG CHAMBERS', supervisor: 'TONY GARRETT' },
    { value: 'DOUG CRANER', supervisor: 'ADRIAN EADS' },
    { value: 'DRAPER', supervisor: 'TRANSITION' },
    { value: 'DUSTIN ANDERSON', supervisor: 'WADE ALLINSON' },
    { value: 'DUSTIN APPEL', supervisor: 'ANNETTE SALGADO' },
    { value: 'DUSTIN R. VEATER', supervisor: 'ALLEN JULIAN' },
    { value: 'ELDON HAMELIN', supervisor: 'WADE ALLINSON' },
    { value: 'ERIC PRICE', supervisor: 'SPENCER TURLEY' },
    { value: 'ERIC S JACOBSON', supervisor: 'STEVE WILLIAMSON' },
    { value: 'ERICK LEBRON', supervisor: 'JEFF SHARDLOW' },
    { value: 'ERIK OLSEN', supervisor: 'KILEY D WILLIS' },
    { value: 'EROS AREVALO', supervisor: 'GREG SMITH' },
    { value: 'EVERETT M GIST', supervisor: 'JAMES CLEGG' },
    { value: 'EVERETT WESTERMAN', supervisor: 'DAVID TRAHAN' },
    { value: 'FELICIA LAGARCE', supervisor: 'NATHAN GRIFFITHS' },
    { value: 'FERNANDO SANTANA', supervisor: 'FELICIA LAGARCE' },
    { value: 'GAIL ROSKELLEY', supervisor: 'KIRK LAMBERT' },
    { value: 'GALIT LEVANON-ARELLANO', supervisor: 'KODY FLOYD' },
    { value: 'GERIT ASAY', supervisor: 'KATIE CARVER' },
    { value: 'GLENN C. SMITH', supervisor: 'KIRK LAMBERT' },
    { value: 'GRANT GUSTAVESON', supervisor: 'ROBERT CID' },
    { value: 'GREG HUNT', supervisor: 'DANIEL HAYS' },
    { value: 'GREG OWENS', supervisor: 'GREGORY PERRY' },
    { value: 'GREGORY PERRY', supervisor: 'IRVIN B. HALE' },
    { value: 'HEATHER WEST', supervisor: 'ADRIAN EADS' },
    { value: 'JACKIE GODFREY', supervisor: 'KIM BELL-HOLDEN' },
    { value: 'JAEME SOLIS', supervisor: 'DANIEL HAYS' },
    { value: 'JAKE DOWNS', supervisor: 'NULL' },
    { value: 'JAKE DOWNS', supervisor: 'KIM BELL-HOLDEN' },
    { value: 'JAMES ADAMSON', supervisor: 'DENNIS FRANKLIN' },
    { value: 'JAMES CAMPOS', supervisor: 'STEVE YEATES' },
    { value: 'JAMES GARRETT', supervisor: 'DAVID LOWRY' },
    { value: 'JAMES LEGORE', supervisor: 'MICHAEL RENCKERT' },
    { value: 'JAMES WEAVER', supervisor: 'VIDA BETTS' },
    { value: 'JANECA KLAYKO', supervisor: 'ALBERT WHITEHORSE' },
    { value: 'JARED BONKOSKY', supervisor: 'JEFF SHARDLOW' },
    { value: 'JARED FREEMAN', supervisor: 'BLAKE BEESLEY' },
    { value: 'JARED M. MINNOCH', supervisor: 'JAMES CAMPOS' },
    { value: 'JARED ROSE', supervisor: 'KIM BELL-HOLDEN' },
    { value: 'JARROD L. IRVIN', supervisor: 'KIM BELL-HOLDEN' },
    { value: 'JASON BEHUNIN', supervisor: 'STEVE WILLIAMSON' },
    { value: 'JASON HANSEN', supervisor: 'RYAN PROCTOR' },
    { value: 'JASON ROOTHOFF', supervisor: 'RANDI CARTER' },
    { value: 'JAY L COATES', supervisor: 'KATIE CARVER' },
    { value: 'JAY ROSS', supervisor: 'STEVE WILLIAMSON' },
    { value: 'JEFF SHARDLOW', supervisor: 'NATHAN GRIFFITHS' },
    { value: 'JEFFERY T HOWCROFT', supervisor: 'FELICIA LAGARCE' },
    { value: 'JEFFREY P HUME', supervisor: 'ROBERT CID' },
    { value: 'JEREMY N JUSTICE', supervisor: 'JASON LOERTSCHER' },
    { value: 'JEREMY NELSON', supervisor: 'KIRK LAMBERT' },
    { value: 'JEROMY SAMPSON', supervisor: 'BRIAN HAMBLIN' },
    { value: 'JERRY BORROWMAN', supervisor: 'RICHARD GLEN MORRIS' },
    { value: 'JERRY COOK', supervisor: 'ANNETTE SALGADO' },
    { value: 'JESS A. PLOUZEK', supervisor: 'FELICIA LAGARCE' },
    { value: 'JESSICA COOK', supervisor: 'DANIEL BLANCHARD' },
    { value: 'JOE A MURPHY', supervisor: 'KILEY D WILLIS' },
    { value: 'JOHN B WHITED', supervisor: 'ERIC PRICE' },
    { value: 'JOHN CARPENTER', supervisor: 'SPENCER TURLEY' },
    { value: 'JOHN KELLEY', supervisor: 'BRIAN HAMBLIN' },
    { value: 'JOHN OSEGUERA', supervisor: 'ANGELA HENDRIX' },
    { value: 'JOHN POWELL', supervisor: 'VIDA BETTS' },
    { value: 'JOHNATHAN VASQUEZ', supervisor: 'VIDA BETTS' },
    { value: 'JON KELLY MAXWELL', supervisor: 'DAVID LOWRY' },
    { value: 'JONATHAN SMITH', supervisor: 'JEFF SHARDLOW' },
    { value: 'JORDAN P BONYAI', supervisor: 'CLINTON LUND' },
    { value: 'JOSEPH C ABBOTT', supervisor: 'PRESTON KAY' },
    { value: 'JOSEPH F. LANEY', supervisor: 'ALBERT WHITEHORSE' },
    { value: 'JOSEPH HERMAN', supervisor: 'JEFF SHARDLOW' },
    { value: 'JOSLYN PILLING', supervisor: 'IRVIN B. HALE' },
    { value: 'JUSTIN SCHELIN', supervisor: 'TONY GARRETT' },
    { value: 'KACEN GUBLER', supervisor: 'RICHARD GLEN MORRIS' },
    { value: 'KAREN PREVEDEL', supervisor: 'BRIAN HAMBLIN' },
    { value: 'KARL NORTH', supervisor: 'ROBERT CID' },
    { value: 'KARSON WELCH', supervisor: 'RANDI CARTER' },
    { value: 'KATHY SCOTT', supervisor: 'MICHAEL RENCKERT' },
    { value: 'KAYE HOUSTON', supervisor: 'LEEANN DUNFORD' },
    { value: 'KELEPI VAEA', supervisor: 'GREG SMITH' },
    { value: 'KELLY GARDNER', supervisor: 'STEVE WILLIAMSON' },
    { value: 'KENNETH COX', supervisor: 'GREGORY PERRY' },
    { value: 'KERRIE TURRILL', supervisor: 'ALLEN JULIAN' },
    { value: 'KERRIE TURRILL', supervisor: 'NULL' },
    { value: 'KEVIN HIZER', supervisor: 'CLINTON LUND' },
    { value: 'KEVIN LARSEN', supervisor: 'RICHARD GLEN MORRIS' },
    { value: 'KEVIN MORRIS', supervisor: 'ANGELA HENDRIX' },
    { value: 'KIM SEEGMILLER', supervisor: 'RICHARD GLEN MORRIS' },
    { value: 'KIMBERLY RODELL', supervisor: 'RANDI CARTER' },
    { value: 'KIRK LAMBERT', supervisor: 'KARL KENNINGTON' },
    { value: 'KODY MERRITT', supervisor: 'SETH ROBINSON' },
    { value: 'KRYSTAL D. WIDNER', supervisor: 'ELDON HAMELIN' },
    { value: 'KURT JARMAN', supervisor: 'PRESTON KAY' },
    { value: 'KYLE CELAURO', supervisor: 'BRIAN HAMBLIN' },
    { value: 'KYLE GROVES', supervisor: 'ERIC PRICE' },
    { value: 'LEIONI IKA', supervisor: 'RICHARD GLEN MORRIS' },
    { value: 'LEISA BANKHEAD', supervisor: 'BLAKE BEESLEY' },
    { value: 'LIBERTY YATES', supervisor: 'RANDI CARTER' },
    { value: 'LINDSEY CALL', supervisor: 'JAMES CLEGG' },
    { value: 'LUKE LASSITER', supervisor: 'ELDON HAMELIN' },
    { value: 'LYNDA HAMILTON', supervisor: 'FELICIA LAGARCE' },
    { value: 'M. BRENT WEBB', supervisor: 'MARK COLBY' },
    { value: 'MARC MILLER', supervisor: 'KIRK LAMBERT' },
    { value: 'MARIANNE KIM', supervisor: 'JOSHUA DRAPER' },
    { value: 'MARIETTE MARDIROSIAN', supervisor: 'JEFF SHARDLOW' },
    { value: 'MARK OTTESEN', supervisor: 'CLINTON LUND' },
    { value: 'MATT HAUN', supervisor: 'GREGORY PERRY' },
    { value: 'MATTHEW FAIRBANK', supervisor: 'ANNETTE SALGADO' },
    { value: 'MATTHEW G FAIRBROTHER', supervisor: 'DANIEL SCHUGK' },
    { value: 'MATTHEW HARDING', supervisor: 'ALLEN JULIAN' },
    { value: 'MATTHEW JENSEN', supervisor: 'JOHN CARPENTER' },
    { value: 'MATTHEW RIGBY', supervisor: 'GREGORY PERRY' },
    { value: 'MEGAN B THOMSON', supervisor: 'GREG SMITH' },
    { value: 'MICHAEL BULLOCK', supervisor: 'GREG SMITH' },
    { value: 'MICHAEL D HIGGINS', supervisor: 'CLINTON LUND' },
    { value: 'MICHAEL RENCKERT', supervisor: 'IRVIN B. HALE' },
    { value: 'MICHAEL WESTWOOD', supervisor: 'ANGELA HENDRIX' },
    { value: 'MIKE BLANKENSHIP', supervisor: 'JOSHUA DRAPER' },
    { value: 'MISTY DALTON', supervisor: 'DAVID TRAHAN' },
    { value: 'MITCHELL CARVER', supervisor: 'PRESTON KAY' },
    { value: 'MORGAN R BOND', supervisor: 'JOHN CARPENTER' },
    { value: 'NATHAN FULUVAKA', supervisor: 'DAVID TRAHAN' },
    { value: 'NATHAN HENRIE', supervisor: 'MICHAEL ADAM' },
    { value: 'Nathan Kota', supervisor: 'DARIN VAN LEEUWEN' },
    { value: 'nathan kota', supervisor: 'KODY FLOYD' },
    { value: 'NEIL SMITH', supervisor: 'JOHN CARPENTER' },
    { value: 'NICHOLAS PEAY', supervisor: 'ERIC PRICE' },
    { value: 'NICK BUNNELL', supervisor: 'ERIC PRICE' },
    { value: 'NICK WARD', supervisor: 'CATHERINE GUNDERSON' },
    { value: 'NOELLE ELDREDGE', supervisor: 'JASON LOERTSCHER' },
    { value: 'NONE', supervisor: 'TRANSITION' },
    { value: 'PAUL DOLGNER', supervisor: 'TONY GARRETT' },
    { value: 'QUINN STICKNEY', supervisor: 'ANNETTE SALGADO' },
    { value: 'RANDI CARTER', supervisor: 'IRVIN B. HALE' },
    { value: 'RANDY HALL', supervisor: 'DAVID LOWRY' },
    { value: 'RAYMOND VITELLI', supervisor: 'JEFF SHARDLOW' },
    { value: 'REID BEAN', supervisor: 'DAVID LOWRY' },
    { value: 'RELEASE/REENTRY', supervisor: 'TRANSITION' },
    { value: 'RICARDO PEDROZA', supervisor: 'ROBERT CID' },
    { value: 'RICHARD BILLINGS', supervisor: 'KEN KELLER' },
    { value: 'RICHARD JENKINS', supervisor: 'JEFF SHARDLOW' },
    { value: 'RICHARD WAGER', supervisor: 'JEFF SHARDLOW' },
    { value: 'RICK COIL', supervisor: 'WADE ALLINSON' },
    { value: 'RICK MANWILL', supervisor: 'JOHN CARPENTER' },
    { value: 'ROBERT CID', supervisor: 'NATHAN GRIFFITHS' },
    { value: 'ROBERT GRAHAM', supervisor: 'BLAKE BEESLEY' },
    { value: 'ROBERT SAMUELS', supervisor: 'JAMES ADAMSON' },
    { value: 'ROBERT T. MAUGHAN', supervisor: 'DARIN VAN LEEUWEN' },
    { value: 'Robert West', supervisor: 'KIM BELL-HOLDEN' },
    { value: 'ROD FULLMER', supervisor: 'DAVID TRAHAN' },
    { value: 'RONNIE RICHEY', supervisor: 'TONY GARRETT' },
    { value: 'ROSARIO RAMSEY', supervisor: 'JOSLYN PILLING' },
    { value: 'RUBEN CERVANTES', supervisor: 'JOSHUA DRAPER' },
    { value: 'RUTH ARRIOLA', supervisor: 'DAN AVIS' },
    { value: 'RYAN A VINCENT', supervisor: 'TONY GARRETT' },
    { value: 'RYAN W. STUBBS', supervisor: 'ANGELA HENDRIX' },
    { value: 'SAM JACKMAN', supervisor: 'JEFF SHARDLOW' },
    { value: 'SAMANTHA KEELE', supervisor: 'NATHAN ELDRIDGE' },
    { value: 'SARAH BAILEY', supervisor: 'WILLIAM LUKE' },
    { value: 'SCOTT C. STEPHENS', supervisor: 'RANDI CARTER' },
    { value: 'SEAN VALEIKA', supervisor: 'SETH ROBINSON' },
    { value: 'SETH PETERSON', supervisor: 'KIRK LAMBERT' },
    { value: 'SHARALEE BOOTHE', supervisor: 'CATHERINE GUNDERSON' },
    { value: 'SHAWN ALTON', supervisor: 'VIDA BETTS' },
    { value: 'SHAWN CHURCH', supervisor: 'JAMES ADAMSON' },
    { value: 'SHAWN COSTON', supervisor: 'ALLEN JULIAN' },
    { value: 'SHAWN FETTERS', supervisor: 'ERIC PRICE' },
    { value: 'SHAWN J BEKKEMELLOM', supervisor: 'TRACY SHOCK' },
    { value: 'SHAWN J HARRIS', supervisor: 'RYAN PROCTOR' },
    { value: 'SHON G LUNT', supervisor: 'JOHN CARPENTER' },
    { value: 'SIMON K FULLER', supervisor: 'KODY FLOYD' },
    { value: 'SITH KIM', supervisor: 'MICHAEL RENCKERT' },
    { value: 'SPENCER DRAKE', supervisor: 'KIM BELL-HOLDEN' },
    { value: 'STEPHEN DOROCIAK', supervisor: 'TERRY BANKS' },
    { value: 'STEPHEN FRANCIS', supervisor: 'JAMES CAMPOS' },
    { value: 'STEPHEN PRIEST', supervisor: 'RANDI CARTER' },
    { value: 'Steve Gourley', supervisor: 'JAMES CLEGG' },
    { value: 'STEVEN OSTLER', supervisor: 'WILLIAM LUKE' },
    { value: 'STEVEN UNSWORTH', supervisor: 'WILLIAM LUKE' },
    { value: 'STUART COMBS', supervisor: 'KILEY D WILLIS' },
    { value: 'TERRY D. LEWIS', supervisor: 'MICHAEL RENCKERT' },
    { value: 'TINA TELA', supervisor: 'ANTHONY BROWN' },
    { value: 'TLEENA CAMPBELL', supervisor: 'JOSHUA DRAPER' },
    { value: 'TODD GRAHAM', supervisor: 'BLAKE BEESLEY' },
    { value: 'TODD HANSEN', supervisor: 'TRACY SHOCK' },
    { value: 'TODD KIRK', supervisor: 'JAMES CLEGG' },
    { value: 'TOLBY POT', supervisor: 'GREG SMITH' },
    { value: 'TOM KOSMACK', supervisor: 'VIDA BETTS' },
    { value: 'TRENT P CHRISTENSEN', supervisor: 'JEFF SHARDLOW' },
    { value: 'TRINA WHITEHEAD', supervisor: 'BRIAN HAMBLIN' },
    { value: 'TROY YATES', supervisor: 'KILEY D WILLIS' },
    { value: 'TYLER CONLEY', supervisor: 'ELDON HAMELIN' },
    { value: 'TYLER J CANOVA', supervisor: 'TERRY BANKS' },
    { value: 'TYLER LLOYD', supervisor: 'KODY FLOYD' },
    { value: 'TYLER RACKHAM', supervisor: 'CLINTON LUND' },
    { value: 'TYSON KOMER', supervisor: 'KIM BELL-HOLDEN' },
    { value: 'TYSON PEPPER', supervisor: 'GREGORY PERRY' },
    { value: 'VIDA BETTS', supervisor: 'WADE ALLINSON' },
    { value: 'WADE ALLINSON', supervisor: 'DANIEL BLANCHARD' },
    { value: 'WAYNE SMITH', supervisor: 'JAMES CLEGG' },
    { value: 'WENDY WARD', supervisor: 'KIRK LAMBERT' },
    { value: 'WESTON MARSHALL', supervisor: 'DAVID LOWRY' },
    { value: 'WILLIAM LUKE', supervisor: 'NATHAN GRIFFITHS' },
    { value: 'WILLIAM MORELL', supervisor: 'GREG SMITH' },
    { value: 'ZACH HUTTO', supervisor: 'KODY FLOYD' },
    { value: 'ZACH THOMAS', supervisor: 'CLINTON LUND' }
];

const supervisors = [
    { value: 'ADRIAN EADS' },
    { value: 'ALBERT WHITEHORSE' },
    { value: 'ALLEN JULIAN' },
    { value: 'ANGELA HENDRIX' },
    { value: 'ANNETTE SALGADO' },
    { value: 'ANTHONY BROWN' },
    { value: 'BLAKE BEESLEY' },
    { value: 'BRIAN HAMBLIN' },
    { value: 'CATHERINE GUNDERSON' },
    { value: 'CLINTON LUND' },
    { value: 'DAN AVIS' },
    { value: 'DANIEL BLANCHARD' },
    { value: 'DANIEL HAYS' },
    { value: 'DANIEL SCHUGK' },
    { value: 'DARIN VAN LEEUWEN' },
    { value: 'DAVID LOWRY' },
    { value: 'DAVID TRAHAN' },
    { value: 'DENNIS FRANKLIN' },
    { value: 'DORIAN WOLFE' },
    { value: 'ELDON HAMELIN' },
    { value: 'ERIC PRICE' },
    { value: 'FELICIA LAGARCE' },
    { value: 'GREG SMITH' },
    { value: 'GREGORY PERRY' },
    { value: 'IRVIN B. HALE' },
    { value: 'JAMES ADAMSON' },
    { value: 'JAMES CAMPOS' },
    { value: 'JAMES CLEGG' },
    { value: 'JASON LOERTSCHER' },
    { value: 'JEFF SHARDLOW' },
    { value: 'JOHN CARPENTER' },
    { value: 'JOSHUA DRAPER' },
    { value: 'JOSLYN PILLING' },
    { value: 'KARL KENNINGTON' },
    { value: 'KATIE CARVER' },
    { value: 'KEN KELLER' },
    { value: 'KILEY D WILLIS' },
    { value: 'KIM BELL-HOLDEN' },
    { value: 'KIRK LAMBERT' },
    { value: 'KODY FLOYD' },
    { value: 'LEEANN DUNFORD' },
    { value: 'MARK COLBY' },
    { value: 'MICHAEL ADAM' },
    { value: 'MICHAEL RENCKERT' },
    { value: 'NATHAN ELDRIDGE' },
    { value: 'NATHAN GRIFFITHS' },
    { value: 'PRESTON KAY' },
    { value: 'RANDI CARTER' },
    { value: 'RICHARD GLEN MORRIS' },
    { value: 'RICK SMITH' },
    { value: 'ROBERT CID' },
    { value: 'RYAN PROCTOR' },
    { value: 'SETH ROBINSON' },
    { value: 'SPENCER TURLEY' },
    { value: 'STEVE WILLIAMSON' },
    { value: 'STEVE YEATES' },
    { value: 'TERRY BANKS' },
    { value: 'TONY GARRETT' },
    { value: 'TRACY SHOCK' },
    { value: 'TRANSITION' },
    { value: 'VIDA BETTS' },
    { value: 'WADE ALLINSON' },
    { value: 'WILLIAM LUKE' }
];

const supervisionContactDays = [30, 60, 90, 180];

export {
    supervisionItems,
    mainGangs,
    offenseTypes,
    agents,
    supervisors,
    supervisionContactDays
};
