import '../Sidebar/Sidebar.css';
import { SpecialSupervision } from './Identify';

export default {
  title: 'Identify/Special Supervision',
  component: SpecialSupervision,
};

export const Normal = () => (
  <SpecialSupervision>
    {{
      address: '1405 Washington Blvd',
      address_start_date: 1535750000000,
      address_type: '1st PHYSICAL',
      agent_name: 'Steve Gourley',
      alerts: 'mean dog',
      cautions: 'lies a lot and has a concealed carry license',
      date_of_birth: 648949400000,
      earned_compliance_credit: 1535750000000,
      employer_address: 'WEST HIGHWAY 40, ROOSEVELT UT 84066',
      employer_phone: '435-722-5650',
      gang_id: null,
      gang_name: 'West Side Players',
      gang_type_id: null,
      offense_code: 'J',
      offense_description: null,
      primary_offense: null,
      race: 'native american/alaskan',
      ccc: 0,
      comp: 0,
      dep: 0,
      dora: 0,
      drugct: 0,
      ecr: 0,
      em: 0,
      fosi: 0,
      fug: 0,
      gps: 0,
      igint: 0,
      incar: 1,
      mio: 1,
      pvp: 0,
      resid: 0,
      so: 0,
      soa: 1,
      sob: 1,
      soc: 1,
      state: 'UT',
      supervision_start_date: 1471327200000,
      unit: '#8',
      crime_degree: 'MA',
      offender_phone: '801-888-0101',
    }}
  </SpecialSupervision>
);
export const Single = () => (
  <SpecialSupervision>
    {{
      address: '1405 Washington Blvd',
      address_start_date: 1535750000000,
      address_type: '1st PHYSICAL',
      agent_name: 'Steve Gourley',
      alerts: 'mean dog',
      cautions: 'lies a lot and has a concealed carry license',
      date_of_birth: 648949400000,
      earned_compliance_credit: 1535750000000,
      employer_address: 'WEST HIGHWAY 40, ROOSEVELT UT 84066',
      employer_phone: '435-722-5650',
      gang_id: null,
      gang_name: 'West Side Players',
      gang_type_id: null,
      offense_code: 'J',
      offense_description: null,
      primary_offense: null,
      race: 'native american/alaskan',
      ccc: 0,
      comp: 0,
      dep: 0,
      dora: 0,
      drugct: 0,
      ecr: 0,
      em: 0,
      fosi: 0,
      fug: 0,
      gps: 0,
      igint: 0,
      incar: 0,
      mio: 0,
      pvp: 0,
      resid: 0,
      so: 0,
      soa: 0,
      sob: 0,
      soc: 1,
      state: 'UT',
      supervision_start_date: 1471327200000,
      unit: '#8',
      crime_degree: 'MA',
      offender_phone: '801-888-0101',
    }}
  </SpecialSupervision>
);
export const Empty = () => (
  <SpecialSupervision>
    {{
      address: '1405 Washington Blvd',
      address_start_date: 1535750000000,
      address_type: '1st PHYSICAL',
      agent_name: 'Steve Gourley',
      alerts: 'mean dog',
      cautions: 'lies a lot and has a concealed carry license',
      date_of_birth: 648949400000,
      earned_compliance_credit: 1535750000000,
      employer_address: 'WEST HIGHWAY 40, ROOSEVELT UT 84066',
      employer_phone: '435-722-5650',
      gang_id: null,
      gang_name: 'West Side Players',
      gang_type_id: null,
      offense_code: 'J',
      offense_description: null,
      primary_offense: null,
      race: 'native american/alaskan',
      ccc: 0,
      comp: 0,
      dep: 0,
      dora: 0,
      drugct: 0,
      ecr: 0,
      em: 0,
      fosi: 0,
      fug: 0,
      gps: 0,
      igint: 0,
      incar: 0,
      mio: 0,
      pvp: 0,
      resid: 0,
      so: 0,
      soa: 0,
      sob: 0,
      soc: 0,
      state: 'UT',
      supervision_start_date: 1471327200000,
      unit: '#8',
      crime_degree: 'MA',
      offender_phone: '801-888-0101',
    }}
  </SpecialSupervision>
);
