#!/usr/bin/env python
# * coding: utf8 *
'''
schema.py
A module that holds the schema for the dat file
'''

SCHEMA = [
    ('offender_id', 'int'),
    ('gender', 'string'),
    ('region_id', 'int'),
    ('agency', 'string'),
    ('supervisor_id', 'string'),
    ('supervisor_name', 'string'),
    ('agent_id', 'string'),
    ('agent_name', 'string'),
    ('offender', 'string'),
    ('dob', 'date'),
    ('race', 'string'),
    ('legal_type', 'string'),
    ('legal_class', 'string'),
    ('legal_status', 'string'),
    ('supervision_start_date', 'date'),
    ('offender_location', 'string'),
    ('address_start_date', 'date'),
    ('address', 'string'),
    ('unit', 'string'),
    ('city', 'string'),
    ('state', 'string'),
    ('zip', 'string'),
    ('address_type_code', 'string'),
    ('address_type', 'string'),
    ('x', 'float'),
    ('y', 'float'),
    ('score', 'float'),
    ('offender_phone', 'string'),
    ('standard_of_supervision', 'string'),
    ('special_supervision', 'string'),
    ('last_office_contact', 'date'),
    ('last_successful_field_contact', 'date'),
    ('last_field_contact', 'date'),
    ('field_contact_result', 'string'),
    ('offense_code', 'string'),
    ('offense_type', 'string'),
    ('crime_degree', 'string'),
    ('offense', 'string'),
    ('ecc', 'date'),
    ('active_warrant', 'bit'),
    ('employer', 'string'),
    ('stg_id', 'int'),
    ('stg_name', 'string'),
    ('stg_type_id', 'int'),
    ('stg_type', 'string'),
]
