ignoredBuiltDependencies:
  - '@vaadin/vaadin-usage-statistics'

onlyBuiltDependencies:
  - '@firebase/util'
  - esbuild
  - protobufjs

overrides:
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  happy-dom@<20.0.0: '>=20.0.0'
  happy-dom@<20.0.2: '>=20.0.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  lodash-es@>=4.0.0 <=4.17.22: '>=4.17.23'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  storybook@>=10.0.0 <10.1.10: '>=10.1.10'
  tmp@<=0.2.3: '>=0.2.4'
